services:
  # Apps
  # - Web
  app-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: sanipatitas-web
    ports:
      - "4321:80"
    depends_on:
      - service-auth

  # Services
  # - Auth
  service-auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: sanipatitas-auth
    env_file: services/auth/.env
    ports:
      - "3000:3000"
    depends_on:
      - database-sql
      - database-redis

  # - Core
  service-core:
    build:
      context: .
      dockerfile: services/core/Dockerfile
    container_name: sanipatitas-core
    env_file: services/core/.env
    ports:
      - "8080:8080"
    depends_on:
      - database-sql
      - database-redis

  # Databases
  # - SQL
  database-sql:
    image: postgres:17-alpine
    container_name: sanipatitas-db
    environment:
      TZ: America/Lima
      POSTGRES_USER: sanipatitas-user
      POSTGRES_PASSWORD: sanipatitas-password
      POSTGRES_DB: sanipatitas-db
    ports:
      - "5432:5432"
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 10

  # - SQL Studio
  database-sql-studio:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: sanipatitas-db-studio
    environment:
      TZ: America/Lima
      DATABASE_URL_APP: postgres://sanipatitas-user:sanipatitas-password@database-sql:5432/sanipatitas-db
      STORE_PATH: /data
    volumes:
      - sanipatitas-sql-studio-data:/data
    ports:
      - "4983:4983"

  # - Redis
  database-redis:
    image: redis:7-alpine
    container_name: sanipatitas-redis
    environment:
      TZ: America/Lima
    ports:
      - "6379:6379"
    healthcheck:
      test:
        - CMD-SHELL
        - "redis-cli ping"
      interval: 5s
      timeout: 5s
      retries: 10

  # - Redis Studio
  database-redis-studio:
    image: redis/redisinsight:latest
    container_name: sanipatitas-redis-studio
    environment:
      TZ: America/Lima
      RI_REDIS_HOST_APP: database-redis
    ports:
      - "5540:5540"

volumes:
  sanipatitas-sql-studio-data:
