# App
quarkus.banner.enabled=false
quarkus.http.port=8081
# Dev
quarkus.compose.devservices.files=../../docker-compose-devservices.yaml
%dev.quarkus.compose.devservices.enabled=false
%dev.quarkus.compose.devservices.profiles=dev
# Test
%test.quarkus.compose.devservices.profiles=test
# Cors
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=tauri://localhost,http://tauri.localhost
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.exposed-headers=Content-Disposition
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.access-control-max-age=24H
%dev.quarkus.http.cors.origins=tauri://localhost,http://tauri.localhost,http://localhost:1420
# Sql
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
%dev.quarkus.datasource.username=sanipatitas-user
%dev.quarkus.datasource.password=sanipatitas-password
%dev.quarkus.datasource.reactive.url=vertx-reactive:postgresql://host.docker.internal:5432/sanipatitas-db?loggerLevel=OFF
# Cache
%dev.quarkus.redis.hosts=redis://host.docker.internal:6379
# JWT
mp.jwt.verify.publickey.algorithm=ES256
smallrye.jwt.claims.groups=role
smallrye.jwt.path.groups=role
%dev.mp.jwt.verify.publickey.location=http://localhost/api/auth/jwks
%dev.mp.jwt.verify.issuer=http://localhost
%dev.mp.jwt.verify.audiences=http://localhost
# Openapi
quarkus.smallrye-openapi.info-title=Sanipatitas Appointment
quarkus.smallrye-openapi.info-description=API documentation for the Appointment service of Sanipatitas platform.
quarkus.smallrye-openapi.path=/api/appointment/openapi.json
mp.openapi.filter=dev.martindotpy.sanipatitas.shared.core.adapter.openapi.ProblemDetailsRequiredFieldsFilter
%prod.quarkus.smallrye-openapi.enabled=true
# Problem details
quarkus.resteasy.problem.constraint-violation.title=Unprocessable Entity
quarkus.resteasy.problem.constraint-violation.status=422
quarkus.resteasy.problem.constraint-violation.description=Unprocessable Entity: server would not process the request due to something the server considered to be a client error
# Optimization
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
