# App
quarkus.banner.enabled=false
quarkus.compose.devservices.files=../../docker-compose-devservices.yaml
# Dev
%dev.quarkus.compose.devservices.profiles=dev
%dev.quarkus.datasource.username=sanipatitas-user
%dev.quarkus.datasource.password=sanipatitas-password
%dev.quarkus.datasource.reactive.url=vertx-reactive:postgresql://host.docker.internal:5432/sanipatitas-db?loggerLevel=OFF
%dev.quarkus.redis.hosts=redis://host.docker.internal:6379
%dev.mp.jwt.verify.publickey=http://host.docker.internal:3000/api/auth/jwks
%dev.mp.jwt.verify.issuer=http://localhost:4321
%dev.mp.jwt.verify.audiences=http://localhost:4321
# Test
%test.quarkus.compose.devservices.profiles=test
# Hibernate
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
# JWT
mp.jwt.verify.publickey.algorithm=ES256
# Openapi
quarkus.smallrye-openapi.info-title=Sanipatitas Core
quarkus.smallrye-openapi.info-description=API documentation for the Core service of Sanipatitas platform.
quarkus.smallrye-openapi.path=/api/core/openapi.json
mp.openapi.filter=dev.martindotpy.sanipatitas.core.adapter.openapi.ProblemDetailsRequiredFieldsFilter
# Optimization
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=true
