// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdErrors,
  DeleteApiAppointmentByIdResponses,
  DeleteApiBreedByIdData,
  DeleteApiBreedByIdErrors,
  DeleteApiBreedByIdResponses,
  DeleteApiClientByIdData,
  DeleteApiClientByIdErrors,
  DeleteApiClientByIdResponses,
  DeleteApiPatientByIdData,
  DeleteApiPatientByIdErrors,
  DeleteApiPatientByIdResponses,
  DeleteApiSpeciesByIdData,
  DeleteApiSpeciesByIdErrors,
  DeleteApiSpeciesByIdResponses,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdErrors,
  GetApiAppointmentByIdResponses,
  GetApiAppointmentData,
  GetApiAppointmentErrors,
  GetApiAppointmentResponses,
  GetApiAuthAccountInfoData,
  GetApiAuthAccountInfoErrors,
  GetApiAuthAccountInfoResponses,
  GetApiAuthCallbackByIdData,
  GetApiAuthCallbackByIdErrors,
  GetApiAuthDeleteUserCallbackData,
  GetApiAuthDeleteUserCallbackErrors,
  GetApiAuthDeleteUserCallbackResponses,
  GetApiAuthErrorData,
  GetApiAuthErrorErrors,
  GetApiAuthErrorResponses,
  GetApiAuthOkData,
  GetApiAuthOkErrors,
  GetApiAuthOkResponses,
  GetApiAuthVerifyEmailData,
  GetApiAuthVerifyEmailErrors,
  GetApiAuthVerifyEmailResponses,
  GetApiBreedByIdData,
  GetApiBreedByIdErrors,
  GetApiBreedByIdResponses,
  GetApiBreedData,
  GetApiBreedErrors,
  GetApiBreedResponses,
  GetApiClientByIdData,
  GetApiClientByIdErrors,
  GetApiClientByIdResponses,
  GetApiClientData,
  GetApiClientErrors,
  GetApiClientResponses,
  GetApiPatientByIdData,
  GetApiPatientByIdErrors,
  GetApiPatientByIdResponses,
  GetApiPatientData,
  GetApiPatientErrors,
  GetApiPatientResponses,
  GetApiSpeciesByIdData,
  GetApiSpeciesByIdErrors,
  GetApiSpeciesByIdResponses,
  GetApiSpeciesData,
  GetApiSpeciesErrors,
  GetApiSpeciesResponses,
  OpenapiAdminListUserSessionsData,
  OpenapiAdminListUserSessionsErrors,
  OpenapiAdminListUserSessionsResponses,
  OpenapiAdminUpdateUserData,
  OpenapiAdminUpdateUserErrors,
  OpenapiAdminUpdateUserResponses,
  OpenapiBanUserData,
  OpenapiBanUserErrors,
  OpenapiBanUserResponses,
  OpenapiChangeEmailData,
  OpenapiChangeEmailErrors,
  OpenapiChangeEmailResponses,
  OpenapiChangePasswordData,
  OpenapiChangePasswordErrors,
  OpenapiChangePasswordResponses,
  OpenapiCreateUserData,
  OpenapiCreateUserErrors,
  OpenapiCreateUserResponses,
  OpenapiDeleteUserData,
  OpenapiDeleteUserErrors,
  OpenapiDeleteUserResponses,
  OpenapiGetJsonWebKeySetData,
  OpenapiGetJsonWebKeySetErrors,
  OpenapiGetJsonWebKeySetResponses,
  OpenapiGetJsonWebTokenData,
  OpenapiGetJsonWebTokenErrors,
  OpenapiGetJsonWebTokenResponses,
  OpenapiGetSessionData,
  OpenapiGetSessionErrors,
  OpenapiGetSessionPostData,
  OpenapiGetSessionPostErrors,
  OpenapiGetSessionPostResponses,
  OpenapiGetSessionResponses,
  OpenapiGetUserData,
  OpenapiGetUserErrors,
  OpenapiGetUserResponses,
  OpenapiImpersonateUserData,
  OpenapiImpersonateUserErrors,
  OpenapiImpersonateUserResponses,
  OpenapiLinkSocialAccountData,
  OpenapiLinkSocialAccountErrors,
  OpenapiLinkSocialAccountResponses,
  OpenapiListUserAccountsData,
  OpenapiListUserAccountsErrors,
  OpenapiListUserAccountsResponses,
  OpenapiListUsersData,
  OpenapiListUsersErrors,
  OpenapiListUserSessionsData,
  OpenapiListUserSessionsErrors,
  OpenapiListUserSessionsResponses,
  OpenapiListUsersResponses,
  OpenapiRemoveUserData,
  OpenapiRemoveUserErrors,
  OpenapiRemoveUserResponses,
  OpenapiRequestPasswordResetData,
  OpenapiRequestPasswordResetErrors,
  OpenapiRequestPasswordResetResponses,
  OpenapiResetPasswordCallbackData,
  OpenapiResetPasswordCallbackErrors,
  OpenapiResetPasswordCallbackResponses,
  OpenapiResetPasswordData,
  OpenapiResetPasswordErrors,
  OpenapiResetPasswordResponses,
  OpenapiRevokeUserSessionData,
  OpenapiRevokeUserSessionErrors,
  OpenapiRevokeUserSessionResponses,
  OpenapiRevokeUserSessionsData,
  OpenapiRevokeUserSessionsErrors,
  OpenapiRevokeUserSessionsResponses,
  OpenapiSendVerificationEmailData,
  OpenapiSendVerificationEmailErrors,
  OpenapiSendVerificationEmailResponses,
  OpenapiSetUserPasswordData,
  OpenapiSetUserPasswordErrors,
  OpenapiSetUserPasswordResponses,
  OpenapiSetUserRoleData,
  OpenapiSetUserRoleErrors,
  OpenapiSetUserRoleResponses,
  OpenapiSignInEmailData,
  OpenapiSignInEmailErrors,
  OpenapiSignInEmailResponses,
  OpenapiSignOutData,
  OpenapiSignOutErrors,
  OpenapiSignOutResponses,
  OpenapiSignUpWithEmailAndPasswordData,
  OpenapiSignUpWithEmailAndPasswordErrors,
  OpenapiSignUpWithEmailAndPasswordResponses,
  OpenapiSocialSignInData,
  OpenapiSocialSignInErrors,
  OpenapiSocialSignInResponses,
  OpenapiUnbanUserData,
  OpenapiUnbanUserErrors,
  OpenapiUnbanUserResponses,
  OpenapiUpdateSessionData,
  OpenapiUpdateSessionErrors,
  OpenapiUpdateSessionResponses,
  OpenapiUpdateUserData,
  OpenapiUpdateUserErrors,
  OpenapiUpdateUserResponses,
  OpenapiVerifyPasswordData,
  OpenapiVerifyPasswordErrors,
  OpenapiVerifyPasswordResponses,
  PostApiAppointmentData,
  PostApiAppointmentErrors,
  PostApiAppointmentResponses,
  PostApiAuthAdminHasPermissionData,
  PostApiAuthAdminHasPermissionErrors,
  PostApiAuthAdminHasPermissionResponses,
  PostApiAuthAdminStopImpersonatingData,
  PostApiAuthAdminStopImpersonatingErrors,
  PostApiAuthCallbackByIdData,
  PostApiAuthCallbackByIdErrors,
  PostApiAuthGetAccessTokenData,
  PostApiAuthGetAccessTokenErrors,
  PostApiAuthGetAccessTokenResponses,
  PostApiAuthRefreshTokenData,
  PostApiAuthRefreshTokenErrors,
  PostApiAuthRefreshTokenResponses,
  PostApiAuthRevokeOtherSessionsData,
  PostApiAuthRevokeOtherSessionsErrors,
  PostApiAuthRevokeOtherSessionsResponses,
  PostApiAuthRevokeSessionData,
  PostApiAuthRevokeSessionErrors,
  PostApiAuthRevokeSessionResponses,
  PostApiAuthRevokeSessionsData,
  PostApiAuthRevokeSessionsErrors,
  PostApiAuthRevokeSessionsResponses,
  PostApiAuthUnlinkAccountData,
  PostApiAuthUnlinkAccountErrors,
  PostApiAuthUnlinkAccountResponses,
  PostApiBreedData,
  PostApiBreedErrors,
  PostApiBreedResponses,
  PostApiClientData,
  PostApiClientErrors,
  PostApiClientResponses,
  PostApiPatientData,
  PostApiPatientErrors,
  PostApiPatientResponses,
  PostApiSpeciesData,
  PostApiSpeciesErrors,
  PostApiSpeciesResponses,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdErrors,
  PutApiAppointmentByIdResponses,
  PutApiBreedByIdData,
  PutApiBreedByIdErrors,
  PutApiBreedByIdResponses,
  PutApiClientByIdData,
  PutApiClientByIdErrors,
  PutApiClientByIdResponses,
  PutApiPatientByIdData,
  PutApiPatientByIdErrors,
  PutApiPatientByIdResponses,
  PutApiSpeciesByIdData,
  PutApiSpeciesByIdErrors,
  PutApiSpeciesByIdResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Sign in with a social provider
 */
export const openapiSocialSignIn = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiSocialSignInData, ThrowOnError>
): RequestResult<
  OpenapiSocialSignInResponses,
  OpenapiSocialSignInErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiSocialSignInResponses,
    OpenapiSocialSignInErrors,
    ThrowOnError
  >({
    url: "/api/auth/sign-in/social",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const getApiAuthCallbackById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAuthCallbackByIdData, ThrowOnError>
): RequestResult<unknown, GetApiAuthCallbackByIdErrors, ThrowOnError> =>
  (options.client ?? client).get<
    unknown,
    GetApiAuthCallbackByIdErrors,
    ThrowOnError
  >({ url: "/api/auth/callback/{id}", ...options })

export const postApiAuthCallbackById = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthCallbackByIdData, ThrowOnError>
): RequestResult<unknown, PostApiAuthCallbackByIdErrors, ThrowOnError> =>
  (options.client ?? client).post<
    unknown,
    PostApiAuthCallbackByIdErrors,
    ThrowOnError
  >({
    url: "/api/auth/callback/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get the current session
 */
export const openapiGetSession = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiGetSessionData, ThrowOnError>
): RequestResult<
  OpenapiGetSessionResponses,
  OpenapiGetSessionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    OpenapiGetSessionResponses,
    OpenapiGetSessionErrors,
    ThrowOnError
  >({ url: "/api/auth/get-session", ...options })

/**
 * Get the current session
 */
export const openapiGetSessionPost = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiGetSessionPostData, ThrowOnError>
): RequestResult<
  OpenapiGetSessionPostResponses,
  OpenapiGetSessionPostErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    OpenapiGetSessionPostResponses,
    OpenapiGetSessionPostErrors,
    ThrowOnError
  >({
    url: "/api/auth/get-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Sign out the current user
 */
export const openapiSignOut = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiSignOutData, ThrowOnError>
): RequestResult<OpenapiSignOutResponses, OpenapiSignOutErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    OpenapiSignOutResponses,
    OpenapiSignOutErrors,
    ThrowOnError
  >({
    url: "/api/auth/sign-out",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Sign up a user using email and password
 */
export const openapiSignUpWithEmailAndPassword = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OpenapiSignUpWithEmailAndPasswordData, ThrowOnError>
): RequestResult<
  OpenapiSignUpWithEmailAndPasswordResponses,
  OpenapiSignUpWithEmailAndPasswordErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    OpenapiSignUpWithEmailAndPasswordResponses,
    OpenapiSignUpWithEmailAndPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/sign-up/email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Sign in with email and password
 */
export const openapiSignInEmail = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiSignInEmailData, ThrowOnError>
): RequestResult<
  OpenapiSignInEmailResponses,
  OpenapiSignInEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiSignInEmailResponses,
    OpenapiSignInEmailErrors,
    ThrowOnError
  >({
    url: "/api/auth/sign-in/email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Reset the password for a user
 */
export const openapiResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiResetPasswordData, ThrowOnError>
): RequestResult<
  OpenapiResetPasswordResponses,
  OpenapiResetPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiResetPasswordResponses,
    OpenapiResetPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Verify the current user's password
 */
export const openapiVerifyPassword = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiVerifyPasswordData, ThrowOnError>
): RequestResult<
  OpenapiVerifyPasswordResponses,
  OpenapiVerifyPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiVerifyPasswordResponses,
    OpenapiVerifyPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/verify-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Verify the email of the user
 */
export const getApiAuthVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAuthVerifyEmailData, ThrowOnError>
): RequestResult<
  GetApiAuthVerifyEmailResponses,
  GetApiAuthVerifyEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiAuthVerifyEmailResponses,
    GetApiAuthVerifyEmailErrors,
    ThrowOnError
  >({ url: "/api/auth/verify-email", ...options })

/**
 * Send a verification email to the user
 */
export const openapiSendVerificationEmail = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<OpenapiSendVerificationEmailData, ThrowOnError>
): RequestResult<
  OpenapiSendVerificationEmailResponses,
  OpenapiSendVerificationEmailErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    OpenapiSendVerificationEmailResponses,
    OpenapiSendVerificationEmailErrors,
    ThrowOnError
  >({
    url: "/api/auth/send-verification-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

export const openapiChangeEmail = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiChangeEmailData, ThrowOnError>
): RequestResult<
  OpenapiChangeEmailResponses,
  OpenapiChangeEmailErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiChangeEmailResponses,
    OpenapiChangeEmailErrors,
    ThrowOnError
  >({
    url: "/api/auth/change-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Change the password of the user
 */
export const openapiChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiChangePasswordData, ThrowOnError>
): RequestResult<
  OpenapiChangePasswordResponses,
  OpenapiChangePasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiChangePasswordResponses,
    OpenapiChangePasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update the current session
 */
export const openapiUpdateSession = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiUpdateSessionData, ThrowOnError>
): RequestResult<
  OpenapiUpdateSessionResponses,
  OpenapiUpdateSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiUpdateSessionResponses,
    OpenapiUpdateSessionErrors,
    ThrowOnError
  >({
    url: "/api/auth/update-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update the current user
 */
export const openapiUpdateUser = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiUpdateUserData, ThrowOnError>
): RequestResult<
  OpenapiUpdateUserResponses,
  OpenapiUpdateUserErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    OpenapiUpdateUserResponses,
    OpenapiUpdateUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/update-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete the user
 */
export const openapiDeleteUser = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiDeleteUserData, ThrowOnError>
): RequestResult<
  OpenapiDeleteUserResponses,
  OpenapiDeleteUserErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    OpenapiDeleteUserResponses,
    OpenapiDeleteUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/delete-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Send a password reset email to the user
 */
export const openapiRequestPasswordReset = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OpenapiRequestPasswordResetData, ThrowOnError>
): RequestResult<
  OpenapiRequestPasswordResetResponses,
  OpenapiRequestPasswordResetErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiRequestPasswordResetResponses,
    OpenapiRequestPasswordResetErrors,
    ThrowOnError
  >({
    url: "/api/auth/request-password-reset",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Redirects the user to the callback URL with the token
 */
export const openapiResetPasswordCallback = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OpenapiResetPasswordCallbackData, ThrowOnError>
): RequestResult<
  OpenapiResetPasswordCallbackResponses,
  OpenapiResetPasswordCallbackErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    OpenapiResetPasswordCallbackResponses,
    OpenapiResetPasswordCallbackErrors,
    ThrowOnError
  >({ url: "/api/auth/reset-password/{token}", ...options })

/**
 * List all active sessions for the user
 */
export const openapiListUserSessions = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiListUserSessionsData, ThrowOnError>
): RequestResult<
  OpenapiListUserSessionsResponses,
  OpenapiListUserSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    OpenapiListUserSessionsResponses,
    OpenapiListUserSessionsErrors,
    ThrowOnError
  >({ url: "/api/auth/list-sessions", ...options })

/**
 * Revoke a single session
 */
export const postApiAuthRevokeSession = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthRevokeSessionData, ThrowOnError>
): RequestResult<
  PostApiAuthRevokeSessionResponses,
  PostApiAuthRevokeSessionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostApiAuthRevokeSessionResponses,
    PostApiAuthRevokeSessionErrors,
    ThrowOnError
  >({
    url: "/api/auth/revoke-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Revoke all sessions for the user
 */
export const postApiAuthRevokeSessions = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiAuthRevokeSessionsData, ThrowOnError>
): RequestResult<
  PostApiAuthRevokeSessionsResponses,
  PostApiAuthRevokeSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostApiAuthRevokeSessionsResponses,
    PostApiAuthRevokeSessionsErrors,
    ThrowOnError
  >({
    url: "/api/auth/revoke-sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Revoke all other sessions for the user except the current one
 */
export const postApiAuthRevokeOtherSessions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiAuthRevokeOtherSessionsData, ThrowOnError>
): RequestResult<
  PostApiAuthRevokeOtherSessionsResponses,
  PostApiAuthRevokeOtherSessionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostApiAuthRevokeOtherSessionsResponses,
    PostApiAuthRevokeOtherSessionsErrors,
    ThrowOnError
  >({
    url: "/api/auth/revoke-other-sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Link a social account to the user
 */
export const openapiLinkSocialAccount = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiLinkSocialAccountData, ThrowOnError>
): RequestResult<
  OpenapiLinkSocialAccountResponses,
  OpenapiLinkSocialAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiLinkSocialAccountResponses,
    OpenapiLinkSocialAccountErrors,
    ThrowOnError
  >({
    url: "/api/auth/link-social",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List all accounts linked to the user
 */
export const openapiListUserAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiListUserAccountsData, ThrowOnError>
): RequestResult<
  OpenapiListUserAccountsResponses,
  OpenapiListUserAccountsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    OpenapiListUserAccountsResponses,
    OpenapiListUserAccountsErrors,
    ThrowOnError
  >({ url: "/api/auth/list-accounts", ...options })

/**
 * Callback to complete user deletion with verification token
 */
export const getApiAuthDeleteUserCallback = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiAuthDeleteUserCallbackData, ThrowOnError>
): RequestResult<
  GetApiAuthDeleteUserCallbackResponses,
  GetApiAuthDeleteUserCallbackErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiAuthDeleteUserCallbackResponses,
    GetApiAuthDeleteUserCallbackErrors,
    ThrowOnError
  >({ url: "/api/auth/delete-user/callback", ...options })

/**
 * Unlink an account
 */
export const postApiAuthUnlinkAccount = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthUnlinkAccountData, ThrowOnError>
): RequestResult<
  PostApiAuthUnlinkAccountResponses,
  PostApiAuthUnlinkAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAuthUnlinkAccountResponses,
    PostApiAuthUnlinkAccountErrors,
    ThrowOnError
  >({
    url: "/api/auth/unlink-account",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Refresh the access token using a refresh token
 */
export const postApiAuthRefreshToken = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthRefreshTokenData, ThrowOnError>
): RequestResult<
  PostApiAuthRefreshTokenResponses,
  PostApiAuthRefreshTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAuthRefreshTokenResponses,
    PostApiAuthRefreshTokenErrors,
    ThrowOnError
  >({
    url: "/api/auth/refresh-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postApiAuthGetAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAuthGetAccessTokenData, ThrowOnError>
): RequestResult<
  PostApiAuthGetAccessTokenResponses,
  PostApiAuthGetAccessTokenErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAuthGetAccessTokenResponses,
    PostApiAuthGetAccessTokenErrors,
    ThrowOnError
  >({
    url: "/api/auth/get-access-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get the account info provided by the provider
 */
export const getApiAuthAccountInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthAccountInfoData, ThrowOnError>
): RequestResult<
  GetApiAuthAccountInfoResponses,
  GetApiAuthAccountInfoErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiAuthAccountInfoResponses,
    GetApiAuthAccountInfoErrors,
    ThrowOnError
  >({ url: "/api/auth/account-info", ...options })

/**
 * Check if the API is working
 */
export const getApiAuthOk = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthOkData, ThrowOnError>
): RequestResult<GetApiAuthOkResponses, GetApiAuthOkErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiAuthOkResponses,
    GetApiAuthOkErrors,
    ThrowOnError
  >({ url: "/api/auth/ok", ...options })

/**
 * Displays an error page
 */
export const getApiAuthError = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAuthErrorData, ThrowOnError>
): RequestResult<
  GetApiAuthErrorResponses,
  GetApiAuthErrorErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiAuthErrorResponses,
    GetApiAuthErrorErrors,
    ThrowOnError
  >({ url: "/api/auth/error", ...options })

/**
 * Set the role of a user
 */
export const openapiSetUserRole = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiSetUserRoleData, ThrowOnError>
): RequestResult<
  OpenapiSetUserRoleResponses,
  OpenapiSetUserRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiSetUserRoleResponses,
    OpenapiSetUserRoleErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/set-role",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get an existing user
 */
export const openapiGetUser = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiGetUserData, ThrowOnError>
): RequestResult<OpenapiGetUserResponses, OpenapiGetUserErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    OpenapiGetUserResponses,
    OpenapiGetUserErrors,
    ThrowOnError
  >({ url: "/api/auth/admin/get-user", ...options })

/**
 * Create a new user
 */
export const openapiCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiCreateUserData, ThrowOnError>
): RequestResult<
  OpenapiCreateUserResponses,
  OpenapiCreateUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiCreateUserResponses,
    OpenapiCreateUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/create-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update a user's details
 */
export const openapiAdminUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiAdminUpdateUserData, ThrowOnError>
): RequestResult<
  OpenapiAdminUpdateUserResponses,
  OpenapiAdminUpdateUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiAdminUpdateUserResponses,
    OpenapiAdminUpdateUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/update-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List users
 */
export const openapiListUsers = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiListUsersData, ThrowOnError>
): RequestResult<
  OpenapiListUsersResponses,
  OpenapiListUsersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    OpenapiListUsersResponses,
    OpenapiListUsersErrors,
    ThrowOnError
  >({ url: "/api/auth/admin/list-users", ...options })

/**
 * List user sessions
 */
export const openapiAdminListUserSessions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OpenapiAdminListUserSessionsData, ThrowOnError>
): RequestResult<
  OpenapiAdminListUserSessionsResponses,
  OpenapiAdminListUserSessionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiAdminListUserSessionsResponses,
    OpenapiAdminListUserSessionsErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/list-user-sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Unban a user
 */
export const openapiUnbanUser = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiUnbanUserData, ThrowOnError>
): RequestResult<
  OpenapiUnbanUserResponses,
  OpenapiUnbanUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiUnbanUserResponses,
    OpenapiUnbanUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/unban-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Ban a user
 */
export const openapiBanUser = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiBanUserData, ThrowOnError>
): RequestResult<OpenapiBanUserResponses, OpenapiBanUserErrors, ThrowOnError> =>
  (options.client ?? client).post<
    OpenapiBanUserResponses,
    OpenapiBanUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/ban-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Impersonate a user
 */
export const openapiImpersonateUser = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiImpersonateUserData, ThrowOnError>
): RequestResult<
  OpenapiImpersonateUserResponses,
  OpenapiImpersonateUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiImpersonateUserResponses,
    OpenapiImpersonateUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/impersonate-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

export const postApiAuthAdminStopImpersonating = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiAuthAdminStopImpersonatingData, ThrowOnError>
): RequestResult<
  unknown,
  PostApiAuthAdminStopImpersonatingErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    unknown,
    PostApiAuthAdminStopImpersonatingErrors,
    ThrowOnError
  >({ url: "/api/auth/admin/stop-impersonating", ...options })

/**
 * Revoke a user session
 */
export const openapiRevokeUserSession = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiRevokeUserSessionData, ThrowOnError>
): RequestResult<
  OpenapiRevokeUserSessionResponses,
  OpenapiRevokeUserSessionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiRevokeUserSessionResponses,
    OpenapiRevokeUserSessionErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/revoke-user-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Revoke all user sessions
 */
export const openapiRevokeUserSessions = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiRevokeUserSessionsData, ThrowOnError>
): RequestResult<
  OpenapiRevokeUserSessionsResponses,
  OpenapiRevokeUserSessionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiRevokeUserSessionsResponses,
    OpenapiRevokeUserSessionsErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/revoke-user-sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a user and all their sessions and accounts. Cannot be undone.
 */
export const openapiRemoveUser = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiRemoveUserData, ThrowOnError>
): RequestResult<
  OpenapiRemoveUserResponses,
  OpenapiRemoveUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiRemoveUserResponses,
    OpenapiRemoveUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/remove-user",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Set a user's password
 */
export const openapiSetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<OpenapiSetUserPasswordData, ThrowOnError>
): RequestResult<
  OpenapiSetUserPasswordResponses,
  OpenapiSetUserPasswordErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    OpenapiSetUserPasswordResponses,
    OpenapiSetUserPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/set-user-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Check if the user has permission
 */
export const postApiAuthAdminHasPermission = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiAuthAdminHasPermissionData, ThrowOnError>
): RequestResult<
  PostApiAuthAdminHasPermissionResponses,
  PostApiAuthAdminHasPermissionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostApiAuthAdminHasPermissionResponses,
    PostApiAuthAdminHasPermissionErrors,
    ThrowOnError
  >({
    url: "/api/auth/admin/has-permission",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Get the JSON Web Key Set
 */
export const openapiGetJsonWebKeySet = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiGetJsonWebKeySetData, ThrowOnError>
): RequestResult<
  OpenapiGetJsonWebKeySetResponses,
  OpenapiGetJsonWebKeySetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    OpenapiGetJsonWebKeySetResponses,
    OpenapiGetJsonWebKeySetErrors,
    ThrowOnError
  >({ url: "/api/auth/jwks", ...options })

/**
 * Get a JWT token
 */
export const openapiGetJsonWebToken = <ThrowOnError extends boolean = false>(
  options?: Options<OpenapiGetJsonWebTokenData, ThrowOnError>
): RequestResult<
  OpenapiGetJsonWebTokenResponses,
  OpenapiGetJsonWebTokenErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    OpenapiGetJsonWebTokenResponses,
    OpenapiGetJsonWebTokenErrors,
    ThrowOnError
  >({ url: "/api/auth/token", ...options })

/**
 * Search
 */
export const getApiBreed = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiBreedData, ThrowOnError>
): RequestResult<GetApiBreedResponses, GetApiBreedErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiBreedResponses,
    GetApiBreedErrors,
    ThrowOnError
  >({ url: "/api/breed", ...options })

/**
 * Create
 */
export const postApiBreed = <ThrowOnError extends boolean = false>(
  options: Options<PostApiBreedData, ThrowOnError>
): RequestResult<PostApiBreedResponses, PostApiBreedErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiBreedResponses,
    PostApiBreedErrors,
    ThrowOnError
  >({
    url: "/api/breed",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 */
export const deleteApiBreedById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiBreedByIdData, ThrowOnError>
): RequestResult<
  DeleteApiBreedByIdResponses,
  DeleteApiBreedByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiBreedByIdResponses,
    DeleteApiBreedByIdErrors,
    ThrowOnError
  >({ url: "/api/breed/{id}", ...options })

/**
 * Get By Id
 */
export const getApiBreedById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiBreedByIdData, ThrowOnError>
): RequestResult<
  GetApiBreedByIdResponses,
  GetApiBreedByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiBreedByIdResponses,
    GetApiBreedByIdErrors,
    ThrowOnError
  >({ url: "/api/breed/{id}", ...options })

/**
 * Update
 */
export const putApiBreedById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiBreedByIdData, ThrowOnError>
): RequestResult<
  PutApiBreedByIdResponses,
  PutApiBreedByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiBreedByIdResponses,
    PutApiBreedByIdErrors,
    ThrowOnError
  >({
    url: "/api/breed/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Search
 */
export const getApiClient = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiClientData, ThrowOnError>
): RequestResult<GetApiClientResponses, GetApiClientErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiClientResponses,
    GetApiClientErrors,
    ThrowOnError
  >({ url: "/api/client", ...options })

/**
 * Create
 */
export const postApiClient = <ThrowOnError extends boolean = false>(
  options: Options<PostApiClientData, ThrowOnError>
): RequestResult<PostApiClientResponses, PostApiClientErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiClientResponses,
    PostApiClientErrors,
    ThrowOnError
  >({
    url: "/api/client",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 */
export const deleteApiClientById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiClientByIdData, ThrowOnError>
): RequestResult<
  DeleteApiClientByIdResponses,
  DeleteApiClientByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiClientByIdResponses,
    DeleteApiClientByIdErrors,
    ThrowOnError
  >({ url: "/api/client/{id}", ...options })

/**
 * Get By Id
 */
export const getApiClientById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiClientByIdData, ThrowOnError>
): RequestResult<
  GetApiClientByIdResponses,
  GetApiClientByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiClientByIdResponses,
    GetApiClientByIdErrors,
    ThrowOnError
  >({ url: "/api/client/{id}", ...options })

/**
 * Update
 */
export const putApiClientById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiClientByIdData, ThrowOnError>
): RequestResult<
  PutApiClientByIdResponses,
  PutApiClientByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiClientByIdResponses,
    PutApiClientByIdErrors,
    ThrowOnError
  >({
    url: "/api/client/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Search
 */
export const getApiPatient = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiPatientData, ThrowOnError>
): RequestResult<GetApiPatientResponses, GetApiPatientErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiPatientResponses,
    GetApiPatientErrors,
    ThrowOnError
  >({ url: "/api/patient", ...options })

/**
 * Create
 */
export const postApiPatient = <ThrowOnError extends boolean = false>(
  options: Options<PostApiPatientData, ThrowOnError>
): RequestResult<PostApiPatientResponses, PostApiPatientErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiPatientResponses,
    PostApiPatientErrors,
    ThrowOnError
  >({
    url: "/api/patient",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 */
export const deleteApiPatientById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiPatientByIdData, ThrowOnError>
): RequestResult<
  DeleteApiPatientByIdResponses,
  DeleteApiPatientByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiPatientByIdResponses,
    DeleteApiPatientByIdErrors,
    ThrowOnError
  >({ url: "/api/patient/{id}", ...options })

/**
 * Get By Id
 */
export const getApiPatientById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiPatientByIdData, ThrowOnError>
): RequestResult<
  GetApiPatientByIdResponses,
  GetApiPatientByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiPatientByIdResponses,
    GetApiPatientByIdErrors,
    ThrowOnError
  >({ url: "/api/patient/{id}", ...options })

/**
 * Update
 */
export const putApiPatientById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiPatientByIdData, ThrowOnError>
): RequestResult<
  PutApiPatientByIdResponses,
  PutApiPatientByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiPatientByIdResponses,
    PutApiPatientByIdErrors,
    ThrowOnError
  >({
    url: "/api/patient/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Search
 */
export const getApiSpecies = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiSpeciesData, ThrowOnError>
): RequestResult<GetApiSpeciesResponses, GetApiSpeciesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetApiSpeciesResponses,
    GetApiSpeciesErrors,
    ThrowOnError
  >({ url: "/api/species", ...options })

/**
 * Create
 */
export const postApiSpecies = <ThrowOnError extends boolean = false>(
  options: Options<PostApiSpeciesData, ThrowOnError>
): RequestResult<PostApiSpeciesResponses, PostApiSpeciesErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostApiSpeciesResponses,
    PostApiSpeciesErrors,
    ThrowOnError
  >({
    url: "/api/species",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 */
export const deleteApiSpeciesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiSpeciesByIdData, ThrowOnError>
): RequestResult<
  DeleteApiSpeciesByIdResponses,
  DeleteApiSpeciesByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiSpeciesByIdResponses,
    DeleteApiSpeciesByIdErrors,
    ThrowOnError
  >({ url: "/api/species/{id}", ...options })

/**
 * Get By Id
 */
export const getApiSpeciesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiSpeciesByIdData, ThrowOnError>
): RequestResult<
  GetApiSpeciesByIdResponses,
  GetApiSpeciesByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiSpeciesByIdResponses,
    GetApiSpeciesByIdErrors,
    ThrowOnError
  >({ url: "/api/species/{id}", ...options })

/**
 * Update
 */
export const putApiSpeciesById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiSpeciesByIdData, ThrowOnError>
): RequestResult<
  PutApiSpeciesByIdResponses,
  PutApiSpeciesByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiSpeciesByIdResponses,
    PutApiSpeciesByIdErrors,
    ThrowOnError
  >({
    url: "/api/species/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Find By Date Range
 */
export const getApiAppointment = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiAppointmentData, ThrowOnError>
): RequestResult<
  GetApiAppointmentResponses,
  GetApiAppointmentErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetApiAppointmentResponses,
    GetApiAppointmentErrors,
    ThrowOnError
  >({ url: "/api/appointment", ...options })

/**
 * Create
 */
export const postApiAppointment = <ThrowOnError extends boolean = false>(
  options: Options<PostApiAppointmentData, ThrowOnError>
): RequestResult<
  PostApiAppointmentResponses,
  PostApiAppointmentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostApiAppointmentResponses,
    PostApiAppointmentErrors,
    ThrowOnError
  >({
    url: "/api/appointment",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete
 */
export const deleteApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiAppointmentByIdData, ThrowOnError>
): RequestResult<
  DeleteApiAppointmentByIdResponses,
  DeleteApiAppointmentByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteApiAppointmentByIdResponses,
    DeleteApiAppointmentByIdErrors,
    ThrowOnError
  >({ url: "/api/appointment/{id}", ...options })

/**
 * Get By Id
 */
export const getApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiAppointmentByIdData, ThrowOnError>
): RequestResult<
  GetApiAppointmentByIdResponses,
  GetApiAppointmentByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetApiAppointmentByIdResponses,
    GetApiAppointmentByIdErrors,
    ThrowOnError
  >({ url: "/api/appointment/{id}", ...options })

/**
 * Update
 */
export const putApiAppointmentById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiAppointmentByIdData, ThrowOnError>
): RequestResult<
  PutApiAppointmentByIdResponses,
  PutApiAppointmentByIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutApiAppointmentByIdResponses,
    PutApiAppointmentByIdErrors,
    ThrowOnError
  >({
    url: "/api/appointment/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
