// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: "http://localhost:8080" | (string & {})
}

export type HelloWorld = {
  message?: string
}

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export type HttpProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance: string
  [key: string]: unknown
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export type HttpValidationProblem = {
  /**
   * A optional URI reference that identifies the problem type
   */
  type?: string
  /**
   * A optional, short, human-readable summary of the problem type
   */
  title?: string
  /**
   * The HTTP status code for this occurrence of the problem
   */
  status: number
  /**
   * A optional human-readable explanation specific to this occurrence of the problem
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem
   */
  instance: string
  /**
   * List of validation constraint violations that occurred
   */
  violations?: Array<Violation>
  [key: string]: unknown
}

/**
 * Validation constraint violation details
 */
export type Violation = {
  /**
   * The field for which the validation failed
   */
  field: string
  /**
   * Part of the http request where the validation error occurred such as query, path, header, form, body
   */
  in: string
  /**
   * Description of the validation error
   */
  message: string
}
