// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

export const zOpenapiUser = z.object({
  id: z.string().readonly(),
  name: z.string(),
  email: z.string(),
  emailVerified: z.boolean().readonly().default(false),
  image: z.string().optional(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  role: z.string().readonly().optional(),
  banned: z.boolean().readonly().optional().default(false),
  banReason: z.string().readonly().optional(),
  banExpires: z.iso.datetime().readonly().optional(),
  lastName: z.string(),
})

export const zOpenapiSession = z.object({
  id: z.string().readonly(),
  expiresAt: z.iso.datetime(),
  token: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  ipAddress: z.string().optional(),
  userAgent: z.string().optional(),
  userId: z.string(),
  impersonatedBy: z.string().readonly().optional(),
})

export const zOpenapiAccount = z.object({
  id: z.string().readonly(),
  accountId: z.string(),
  providerId: z.string(),
  userId: z.string(),
  accessToken: z.string().optional(),
  refreshToken: z.string().optional(),
  idToken: z.string().optional(),
  accessTokenExpiresAt: z.iso.datetime().optional(),
  refreshTokenExpiresAt: z.iso.datetime().optional(),
  scope: z.string().optional(),
  password: z.string().optional(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
})

export const zOpenapiJwks = z.object({
  id: z.string().readonly(),
  publicKey: z.string(),
  privateKey: z.string(),
  createdAt: z.iso.datetime(),
  expiresAt: z.iso.datetime().optional(),
})

export const zOpenapiGender = z.enum(["MALE", "FEMALE", "UNKNOWN"])

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpProblem = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  detail: z.string().optional(),
  instance: z.url(),
})

export const zOpenapiIdType = z.enum(["DNI", "CE", "PASSPORT"])

export const zOpenapiLocalDate = z.iso.date()

export const zOpenapiOffsetDateTime = z.iso.datetime()

export const zOpenapiPatientStatsDto = z.object({
  totalPatients: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
  patientsCreatedToday: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
  patientsCreatedThisMonth: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
  totalClients: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
})

export const zOpenapiDataResponsePatientStatsDto = z.object({
  data: zOpenapiPatientStatsDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiUuid = z
  .uuid()
  .regex(
    /[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/
  )

export const zOpenapiClientDto = z.object({
  id: zOpenapiUuid,
  firstName: z.string().max(100).regex(/\S/),
  lastName: z.string().max(100).regex(/\S/),
  idType: zOpenapiIdType,
  idNumber: z.string().min(6).max(20).regex(/\S/),
  phone: z.string().regex(/\S/),
  phoneAlt: z.string().max(15).optional(),
  email: z.string().max(255).optional(),
  address: z.string().max(500).optional(),
  notes: z.string().max(2000).optional(),
})

export const zOpenapiCreateBreedRequest = z.object({
  id: zOpenapiUuid.optional(),
  name: z.string().max(255).regex(/\S/),
  description: z.string().max(2000).optional(),
  speciesId: zOpenapiUuid,
})

export const zOpenapiCreateClientRequest = z.object({
  id: zOpenapiUuid.optional(),
  firstName: z.string().max(100).regex(/\S/),
  lastName: z.string().max(100).regex(/\S/),
  idType: zOpenapiIdType,
  idNumber: z.string().min(6).max(20).regex(/\S/),
  phone: z.string().max(15).regex(/\S/),
  phoneAlt: z.string().max(15).optional(),
  email: z.string().max(255).optional(),
  address: z.string().max(500).optional(),
  notes: z.string().max(2000).optional(),
})

export const zOpenapiCreatePatientRequest = z.object({
  id: zOpenapiUuid.optional(),
  name: z.string().max(500).regex(/\S/),
  gender: zOpenapiGender.optional(),
  birthDate: zOpenapiLocalDate.optional(),
  approximateAge: z.string().max(50).optional(),
  weightKg: z.number().optional(),
  description: z.string().max(2000).optional(),
  isSterilized: z.boolean().optional(),
  isDeceased: z.boolean().optional(),
  breedId: zOpenapiUuid.optional(),
  clientId: zOpenapiUuid,
})

export const zOpenapiCreateSpeciesRequest = z.object({
  id: zOpenapiUuid.optional(),
  name: z.string().max(255).regex(/\S/),
  description: z.string().max(2000).optional(),
})

export const zOpenapiDataResponseClientDto = z.object({
  data: zOpenapiClientDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseClientDto = z.object({
  data: z.array(zOpenapiClientDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiSpeciesDto = z.object({
  id: zOpenapiUuid,
  name: z.string().max(255).regex(/\S/),
  description: z.string().max(2000).optional(),
})

export const zOpenapiBreedDto = z.object({
  id: zOpenapiUuid,
  name: z.string().max(255).regex(/\S/),
  description: z.string().max(2000).optional(),
  species: zOpenapiSpeciesDto,
})

export const zOpenapiDataResponseBreedDto = z.object({
  data: zOpenapiBreedDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiDataResponseSpeciesDto = z.object({
  data: zOpenapiSpeciesDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseBreedDto = z.object({
  data: z.array(zOpenapiBreedDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseSpeciesDto = z.object({
  data: z.array(zOpenapiSpeciesDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiPatientDto = z.object({
  id: zOpenapiUuid,
  name: z.string().max(500).regex(/\S/),
  gender: zOpenapiGender.optional(),
  birthDate: zOpenapiLocalDate.optional(),
  approximateAge: z.string().max(50).optional(),
  weightKg: z.number().optional(),
  description: z.string().max(2000).optional(),
  isSterilized: z.boolean().optional(),
  isDeceased: z.boolean().optional(),
  createdAt: zOpenapiOffsetDateTime,
  updatedAt: zOpenapiOffsetDateTime,
  breed: zOpenapiBreedDto.optional(),
  client: zOpenapiClientDto,
})

export const zOpenapiDataResponsePatientDto = z.object({
  data: zOpenapiPatientDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponsePatientDto = z.object({
  data: z.array(zOpenapiPatientDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiUpdateBreedRequest = z.object({
  name: z.string().max(255).regex(/\S/),
  description: z.string().max(2000).optional(),
  speciesId: zOpenapiUuid,
})

export const zOpenapiUpdateClientRequest = z.object({
  firstName: z.string().max(100).regex(/\S/),
  lastName: z.string().max(100).regex(/\S/),
  idType: zOpenapiIdType,
  idNumber: z.string().min(6).max(20).regex(/\S/),
  phone: z.string().max(15).regex(/\S/),
  phoneAlt: z.string().max(15).optional(),
  email: z.string().max(255).optional(),
  address: z.string().max(500).optional(),
  notes: z.string().max(2000).optional(),
})

export const zOpenapiUpdatePatientRequest = z.object({
  name: z.string().max(500).regex(/\S/),
  gender: zOpenapiGender.optional(),
  birthDate: zOpenapiLocalDate.optional(),
  approximateAge: z.string().max(50).optional(),
  weightKg: z.number().optional(),
  description: z.string().max(2000).optional(),
  isSterilized: z.boolean().optional(),
  isDeceased: z.boolean().optional(),
  breedId: zOpenapiUuid.optional(),
  clientId: zOpenapiUuid,
})

export const zOpenapiUpdateSpeciesRequest = z.object({
  name: z.string().max(255).regex(/\S/),
  description: z.string().max(2000).optional(),
})

/**
 * Validation constraint violation details
 */
export const zOpenapiViolation = z.object({
  field: z.string(),
  in: z.string(),
  message: z.string(),
})

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export const zOpenapiHttpValidationProblem = z.object({
  type: z.url().optional(),
  title: z.string().optional(),
  status: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    }),
  detail: z.string().optional(),
  instance: z.url(),
  violations: z.array(zOpenapiViolation).optional(),
})

export const zOpenapiConditionSeverity = z.enum(["MILD", "MODERATE", "SEVERE"])

export const zOpenapiConditionStatus = z.enum(["ACTIVE", "RESOLVED", "RELAPSE"])

export const zOpenapiCreateMedicalConditionRequest = z.object({
  id: zOpenapiUuid.optional(),
  name: z.string().max(255).regex(/\S/),
  code: z.string().max(20).optional(),
  description: z.string().max(2000).optional(),
  onsetDate: zOpenapiOffsetDateTime.optional(),
  status: zOpenapiConditionStatus.optional(),
  severity: zOpenapiConditionSeverity.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiCreatePrescriptionItemRequest = z.object({
  id: zOpenapiUuid.optional(),
  medicationName: z.string().max(255).regex(/\S/),
  dosage: z.string().max(100).optional(),
  frequency: z.string().max(100).optional(),
  duration: z.string().max(100).optional(),
  route: z.string().max(100).optional(),
  notes: z.string().max(2000).optional(),
})

export const zOpenapiImmunizationRoute = z.enum([
  "SUBCUTANEOUS",
  "INTRAMUSCULAR",
  "ORAL",
  "INTRADERMAL",
  "TOPICAL",
])

export const zOpenapiImmunizationStatus = z.enum([
  "COMPLETED",
  "ENTERED_IN_ERROR",
  "NOT_DONE",
])

export const zOpenapiLocalDateTime = z.iso.datetime()

export const zOpenapiCreateImmunizationRequest = z.object({
  id: zOpenapiUuid.optional(),
  vaccineCode: z.string().max(20).optional(),
  vaccineName: z.string().max(255).regex(/\S/),
  manufacturer: z.string().max(255).optional(),
  lotNumber: z.string().max(255).optional(),
  expirationDate: zOpenapiLocalDateTime.optional(),
  administrationDate: zOpenapiLocalDateTime,
  doseNumber: z.string().max(50).optional(),
  doseUnit: z.string().max(50).optional(),
  route: zOpenapiImmunizationRoute.optional(),
  site: z.string().max(255).optional(),
  reaction: z.string().max(2000).optional(),
  status: zOpenapiImmunizationStatus.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiObservationCategory = z.enum([
  "VITAL_SIGNS",
  "LABORATORY",
  "EXAM",
  "GENERAL",
])

export const zOpenapiObservationStatus = z.enum([
  "PRELIMINARY",
  "FINAL",
  "AMENDED",
  "CANCELLED",
])

export const zOpenapiCreateMedicalObservationRequest = z.object({
  id: zOpenapiUuid.optional(),
  code: z.string().max(255).optional(),
  value: z.string().max(2000).regex(/\S/),
  unit: z.string().max(100).optional(),
  interpretation: z.string().max(255).optional(),
  bodySite: z.string().max(255).optional(),
  method: z.string().max(255).optional(),
  referenceRange: z.string().max(500).optional(),
  category: zOpenapiObservationCategory.optional(),
  status: zOpenapiObservationStatus.optional(),
  issuedDate: zOpenapiLocalDateTime.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiPrescriptionItemDto = z.object({
  id: zOpenapiUuid,
  medicationName: z.string().regex(/\S/),
  dosage: z.string().optional(),
  frequency: z.string().optional(),
  duration: z.string().optional(),
  route: z.string().optional(),
  notes: z.string().optional(),
  createdAt: zOpenapiLocalDateTime,
  updatedAt: zOpenapiLocalDateTime,
})

export const zOpenapiPrescriptionStatus = z.enum([
  "ACTIVE",
  "COMPLETED",
  "CANCELLED",
])

export const zOpenapiCreatePrescriptionRequest = z.object({
  id: zOpenapiUuid.optional(),
  issueDate: zOpenapiLocalDateTime,
  expirationDate: zOpenapiLocalDateTime.optional(),
  notes: z.string().optional(),
  status: zOpenapiPrescriptionStatus.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
  items: z.array(zOpenapiCreatePrescriptionItemRequest).min(1),
})

export const zOpenapiProcedureCategory = z.enum([
  "SURGICAL",
  "DIAGNOSTIC",
  "THERAPEUTIC",
  "PREVENTIVE",
  "OTHER",
])

export const zOpenapiProcedureStatus = z.enum([
  "PREPARATION",
  "IN_PROGRESS",
  "COMPLETED",
  "ABANDONED",
])

export const zOpenapiCreateProcedureRequest = z.object({
  id: zOpenapiUuid.optional(),
  code: z.string().max(20).optional(),
  name: z.string().max(255).regex(/\S/),
  category: zOpenapiProcedureCategory.optional(),
  reason: z.string().max(2000).optional(),
  outcome: z.string().max(2000).optional(),
  complications: z.string().max(2000).optional(),
  performedDate: zOpenapiLocalDateTime.optional(),
  status: zOpenapiProcedureStatus.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiUpdateImmunizationRequest = z.object({
  vaccineCode: z.string().max(20).optional(),
  vaccineName: z.string().max(255).regex(/\S/),
  manufacturer: z.string().max(255).optional(),
  lotNumber: z.string().max(255).optional(),
  expirationDate: zOpenapiLocalDateTime.optional(),
  administrationDate: zOpenapiLocalDateTime,
  doseNumber: z.string().max(50).optional(),
  doseUnit: z.string().max(50).optional(),
  route: zOpenapiImmunizationRoute.optional(),
  site: z.string().max(255).optional(),
  reaction: z.string().max(2000).optional(),
  status: zOpenapiImmunizationStatus.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiUpdateMedicalConditionRequest = z.object({
  name: z.string().max(255).regex(/\S/),
  code: z.string().max(20).optional(),
  description: z.string().max(2000).optional(),
  onsetDate: zOpenapiOffsetDateTime.optional(),
  status: zOpenapiConditionStatus.optional(),
  severity: zOpenapiConditionSeverity.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiUpdateMedicalObservationRequest = z.object({
  code: z.string().max(255).optional(),
  value: z.string().max(2000).regex(/\S/),
  unit: z.string().max(100).optional(),
  interpretation: z.string().max(255).optional(),
  bodySite: z.string().max(255).optional(),
  method: z.string().max(255).optional(),
  referenceRange: z.string().max(500).optional(),
  category: zOpenapiObservationCategory.optional(),
  status: zOpenapiObservationStatus.optional(),
  issuedDate: zOpenapiLocalDateTime.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiUpdatePrescriptionItemRequest = z.object({
  medicationName: z.string().max(255).regex(/\S/),
  dosage: z.string().max(100).optional(),
  frequency: z.string().max(100).optional(),
  duration: z.string().max(100).optional(),
  route: z.string().max(100).optional(),
  notes: z.string().max(2000).optional(),
})

export const zOpenapiUpdatePrescriptionRequest = z.object({
  issueDate: zOpenapiLocalDateTime,
  expirationDate: zOpenapiLocalDateTime.optional(),
  notes: z.string().optional(),
  status: zOpenapiPrescriptionStatus.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
  items: z.array(zOpenapiUpdatePrescriptionItemRequest).min(1),
})

export const zOpenapiUpdateProcedureRequest = z.object({
  code: z.string().max(20).optional(),
  name: z.string().max(255).regex(/\S/),
  category: zOpenapiProcedureCategory.optional(),
  reason: z.string().max(2000).optional(),
  outcome: z.string().max(2000).optional(),
  complications: z.string().max(2000).optional(),
  performedDate: zOpenapiLocalDateTime.optional(),
  status: zOpenapiProcedureStatus.optional(),
  patientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiUserDto = z.object({
  id: zOpenapiUuid,
  name: z.string().max(255).regex(/\S/),
  email: z.string().max(255).regex(/\S/),
  emailVerified: z.boolean(),
  image: z.string().max(500).optional(),
  role: z.string().max(50).optional(),
  banned: z.boolean().optional(),
  banReason: z.string().max(500).optional(),
  banExpires: zOpenapiOffsetDateTime.optional(),
  lastName: z.string().max(255).regex(/\S/),
  createdAt: zOpenapiOffsetDateTime,
  updatedAt: zOpenapiOffsetDateTime,
})

export const zOpenapiImmunizationDto = z.object({
  id: zOpenapiUuid,
  vaccineCode: z.string().optional(),
  vaccineName: z.string().max(255).regex(/\S/),
  manufacturer: z.string().optional(),
  lotNumber: z.string().optional(),
  expirationDate: zOpenapiLocalDateTime.optional(),
  administrationDate: zOpenapiLocalDateTime,
  doseNumber: z.string().optional(),
  doseUnit: z.string().optional(),
  route: zOpenapiImmunizationRoute.optional(),
  site: z.string().optional(),
  reaction: z.string().optional(),
  status: zOpenapiImmunizationStatus,
  createdAt: zOpenapiLocalDateTime,
  updatedAt: zOpenapiLocalDateTime,
  patient: zOpenapiPatientDto,
  veterinarian: zOpenapiUserDto,
})

export const zOpenapiDataResponseImmunizationDto = z.object({
  data: zOpenapiImmunizationDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiMedicalConditionDto = z.object({
  id: zOpenapiUuid,
  name: z.string().max(255).regex(/\S/),
  code: z.string().optional(),
  description: z.string().max(2000).optional(),
  onsetDate: zOpenapiOffsetDateTime.optional(),
  status: zOpenapiConditionStatus,
  severity: zOpenapiConditionSeverity.optional(),
  createdAt: zOpenapiOffsetDateTime,
  updatedAt: zOpenapiOffsetDateTime,
  patient: zOpenapiPatientDto,
  veterinarian: zOpenapiUserDto,
})

export const zOpenapiDataResponseMedicalConditionDto = z.object({
  data: zOpenapiMedicalConditionDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiMedicalObservationDto = z.object({
  id: zOpenapiUuid,
  code: z.string().optional(),
  value: z.string().max(2000).regex(/\S/),
  unit: z.string().optional(),
  interpretation: z.string().optional(),
  bodySite: z.string().optional(),
  method: z.string().optional(),
  referenceRange: z.string().optional(),
  category: zOpenapiObservationCategory.optional(),
  status: zOpenapiObservationStatus,
  issuedDate: zOpenapiLocalDateTime.optional(),
  createdAt: zOpenapiLocalDateTime,
  updatedAt: zOpenapiLocalDateTime,
  patient: zOpenapiPatientDto,
  veterinarian: zOpenapiUserDto,
})

export const zOpenapiDataResponseMedicalObservationDto = z.object({
  data: zOpenapiMedicalObservationDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseImmunizationDto = z.object({
  data: z.array(zOpenapiImmunizationDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseMedicalConditionDto = z.object({
  data: z.array(zOpenapiMedicalConditionDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseMedicalObservationDto = z.object({
  data: z.array(zOpenapiMedicalObservationDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiPrescriptionDto = z.object({
  id: zOpenapiUuid,
  issueDate: zOpenapiLocalDateTime,
  expirationDate: zOpenapiLocalDateTime.optional(),
  notes: z.string().optional(),
  status: zOpenapiPrescriptionStatus,
  createdAt: zOpenapiLocalDateTime,
  updatedAt: zOpenapiLocalDateTime,
  patient: zOpenapiPatientDto,
  veterinarian: zOpenapiUserDto,
  items: z.array(zOpenapiPrescriptionItemDto),
})

export const zOpenapiDataResponsePrescriptionDto = z.object({
  data: zOpenapiPrescriptionDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponsePrescriptionDto = z.object({
  data: z.array(zOpenapiPrescriptionDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiProcedureDto = z.object({
  id: zOpenapiUuid,
  code: z.string().optional(),
  name: z.string().max(255).regex(/\S/),
  category: zOpenapiProcedureCategory.optional(),
  reason: z.string().max(2000).optional(),
  outcome: z.string().max(2000).optional(),
  complications: z.string().max(2000).optional(),
  performedDate: zOpenapiLocalDateTime.optional(),
  status: zOpenapiProcedureStatus,
  createdAt: zOpenapiLocalDateTime,
  updatedAt: zOpenapiLocalDateTime,
  patient: zOpenapiPatientDto,
  veterinarian: zOpenapiUserDto,
})

export const zOpenapiDataResponseProcedureDto = z.object({
  data: zOpenapiProcedureDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseProcedureDto = z.object({
  data: z.array(zOpenapiProcedureDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiAppointmentClass = z.enum([
  "AMBULATORY",
  "EMERGENCY",
  "HOME_VISIT",
])

export const zOpenapiAppointmentStatus = z.enum([
  "SCHEDULED",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
  "NO_SHOW",
])

export const zOpenapiLocalTime = z.string()

export const zOpenapiAppointmentDto = z.object({
  id: zOpenapiUuid,
  date: zOpenapiLocalDate,
  startTime: zOpenapiLocalTime,
  endTime: zOpenapiLocalTime.optional(),
  status: zOpenapiAppointmentStatus,
  appointmentClass: zOpenapiAppointmentClass,
  reason: z.string().max(2000).optional(),
  notes: z.string().max(2000).optional(),
  createdAt: zOpenapiOffsetDateTime,
  updatedAt: zOpenapiOffsetDateTime,
  patient: zOpenapiPatientDto,
  client: zOpenapiClientDto,
  veterinarian: zOpenapiUserDto,
})

export const zOpenapiAppointmentStatsDto = z.object({
  appointmentsToday: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
  appointmentsTodayByStatus: z.record(
    z.string(),
    z.coerce
      .bigint()
      .min(BigInt("-9223372036854775808"), {
        error: "Invalid value: Expected int64 to be >= -9223372036854775808",
      })
      .max(BigInt("9223372036854775807"), {
        error: "Invalid value: Expected int64 to be <= 9223372036854775807",
      })
  ),
  appointmentsThisMonth: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
  upcomingAppointments: z.array(zOpenapiAppointmentDto),
})

export const zOpenapiCreateAppointmentRequest = z.object({
  id: zOpenapiUuid.optional(),
  date: zOpenapiLocalDate,
  startTime: zOpenapiLocalTime,
  endTime: zOpenapiLocalTime.optional(),
  status: zOpenapiAppointmentStatus,
  appointmentClass: zOpenapiAppointmentClass.optional(),
  reason: z.string().max(2000).optional(),
  notes: z.string().max(2000).optional(),
  patientId: zOpenapiUuid,
  clientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiDataResponseAppointmentDto = z.object({
  data: zOpenapiAppointmentDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiDataResponseAppointmentStatsDto = z.object({
  data: zOpenapiAppointmentStatsDto,
  message: z.string().regex(/\S/),
})

export const zOpenapiPageResponseAppointmentDto = z.object({
  data: z.array(zOpenapiAppointmentDto),
  page: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  size: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  totalElements: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  totalPages: z
    .int()
    .min(-2147483648, {
      error: "Invalid value: Expected int32 to be >= -2147483648",
    })
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional(),
  message: z.string().regex(/\S/),
})

export const zOpenapiType = z.enum(["CREATED", "UPDATED", "DELETED"])

export const zOpenapiAppointmentEvent = z.object({
  appointmentId: zOpenapiUuid.optional(),
  type: zOpenapiType.optional(),
})

export const zOpenapiUpdateAppointmentRequest = z.object({
  date: zOpenapiLocalDate,
  startTime: zOpenapiLocalTime,
  endTime: zOpenapiLocalTime.optional(),
  status: zOpenapiAppointmentStatus,
  appointmentClass: zOpenapiAppointmentClass.optional(),
  reason: z.string().max(2000).optional(),
  notes: z.string().max(2000).optional(),
  patientId: zOpenapiUuid,
  clientId: zOpenapiUuid,
  veterinarianId: zOpenapiUuid,
})

export const zOpenapiUserWritable = z.object({
  name: z.string(),
  email: z.string(),
  image: z.string().optional(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  lastName: z.string(),
})

export const zOpenapiSessionWritable = z.object({
  expiresAt: z.iso.datetime(),
  token: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  ipAddress: z.string().optional(),
  userAgent: z.string().optional(),
  userId: z.string(),
})

export const zOpenapiAccountWritable = z.object({
  accountId: z.string(),
  providerId: z.string(),
  userId: z.string(),
  accessToken: z.string().optional(),
  refreshToken: z.string().optional(),
  idToken: z.string().optional(),
  accessTokenExpiresAt: z.iso.datetime().optional(),
  refreshTokenExpiresAt: z.iso.datetime().optional(),
  scope: z.string().optional(),
  password: z.string().optional(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
})

export const zOpenapiJwksWritable = z.object({
  publicKey: z.string(),
  privateKey: z.string(),
  createdAt: z.iso.datetime(),
  expiresAt: z.iso.datetime().optional(),
})

export const zOpenapiSocialSignInBody = z.object({
  callbackURL: z.string().optional(),
  newUserCallbackURL: z.string().optional(),
  errorCallbackURL: z.string().optional(),
  provider: z.union([
    z.enum([
      "apple",
      "atlassian",
      "cognito",
      "discord",
      "facebook",
      "figma",
      "github",
      "microsoft",
      "google",
      "huggingface",
      "slack",
      "spotify",
      "twitch",
      "twitter",
      "dropbox",
      "kick",
      "linear",
      "linkedin",
      "gitlab",
      "tiktok",
      "reddit",
      "roblox",
      "salesforce",
      "vk",
      "zoom",
      "notion",
      "kakao",
      "naver",
      "line",
      "paybin",
      "paypal",
      "polar",
      "railway",
      "vercel",
      "wechat",
    ]),
    z.string(),
  ]),
  disableRedirect: z.boolean().optional(),
  idToken: z
    .object({
      token: z.string(),
      nonce: z.string().optional(),
      accessToken: z.string().optional(),
      refreshToken: z.string().optional(),
      expiresAt: z.number().optional(),
      user: z
        .object({
          name: z
            .object({
              firstName: z.string().optional(),
              lastName: z.string().optional(),
            })
            .optional(),
          email: z.string().optional(),
        })
        .optional(),
    })
    .optional(),
  scopes: z.array(z.string()).optional(),
  requestSignUp: z.boolean().optional(),
  loginHint: z.string().optional(),
  additionalData: z.record(z.string(), z.unknown()).optional(),
})

/**
 * Returns session details when idToken is provided, or an authorize URL otherwise
 */
export const zOpenapiSocialSignInResponse = z.object({
  token: z.string().optional(),
  user: zOpenapiUser.optional(),
  url: z.string().optional(),
  redirect: z.boolean(),
})

export const zGetApiAuthCallbackByIdPath = z.object({
  id: z.string(),
})

export const zPostApiAuthCallbackByIdBody = z.object({
  code: z.string().optional(),
  error: z.string().optional(),
  device_id: z.string().optional(),
  error_description: z.string().optional(),
  state: z.string().optional(),
  user: z.string().optional(),
})

export const zPostApiAuthCallbackByIdPath = z.object({
  id: z.string(),
})

/**
 * Success
 */
export const zOpenapiGetSessionResponse = z
  .object({
    session: zOpenapiSession,
    user: zOpenapiUser,
  })
  .nullable()

export const zOpenapiGetSessionPostBody = z.record(z.string(), z.unknown())

/**
 * Success
 */
export const zOpenapiGetSessionPostResponse = z
  .object({
    session: zOpenapiSession,
    user: zOpenapiUser,
  })
  .nullable()

export const zOpenapiSignOutBody = z.record(z.string(), z.unknown())

/**
 * Success
 */
export const zOpenapiSignOutResponse = z.object({
  success: z.boolean().optional(),
})

export const zOpenapiSignUpWithEmailAndPasswordBody = z.object({
  name: z.string(),
  email: z.string(),
  password: z.string(),
  image: z.string().optional(),
  callbackURL: z.string().optional(),
  rememberMe: z.boolean().optional(),
})

/**
 * Successfully created user
 */
export const zOpenapiSignUpWithEmailAndPasswordResponse = z.object({
  token: z.string().optional(),
  user: z.object({
    id: z.string(),
    email: z.email(),
    name: z.string(),
    image: z.url().optional(),
    emailVerified: z.boolean(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
  }),
})

export const zOpenapiSignInEmailBody = z.object({
  email: z.string(),
  password: z.string(),
  callbackURL: z.string().optional(),
  rememberMe: z.boolean().optional(),
})

/**
 * Session response when idToken is provided
 */
export const zOpenapiSignInEmailResponse = z.object({
  redirect: z.literal(false),
  token: z.string(),
  url: z.string().optional(),
  user: zOpenapiUser,
})

export const zOpenapiResetPasswordBody = z.object({
  newPassword: z.string(),
  token: z.string().optional(),
})

/**
 * Success
 */
export const zOpenapiResetPasswordResponse = z.object({
  status: z.boolean().optional(),
})

export const zOpenapiVerifyPasswordBody = z.object({
  password: z.string(),
})

/**
 * Success
 */
export const zOpenapiVerifyPasswordResponse = z.object({
  status: z.boolean().optional(),
})

export const zGetApiAuthVerifyEmailQuery = z.object({
  token: z.string(),
  callbackURL: z.string().optional(),
})

/**
 * Success
 */
export const zGetApiAuthVerifyEmailResponse = z.object({
  user: zOpenapiUser,
  status: z.boolean(),
})

export const zOpenapiSendVerificationEmailBody = z.object({
  email: z.string(),
  callbackURL: z.string().optional(),
})

/**
 * Success
 */
export const zOpenapiSendVerificationEmailResponse = z.object({
  status: z.boolean().optional(),
})

export const zOpenapiChangeEmailBody = z.object({
  newEmail: z.string(),
  callbackURL: z.string().optional(),
})

/**
 * Email change request processed successfully
 */
export const zOpenapiChangeEmailResponse = z.object({
  user: zOpenapiUser.optional(),
  status: z.boolean(),
  message: z.enum(["Email updated", "Verification email sent"]).optional(),
})

export const zOpenapiChangePasswordBody = z.object({
  newPassword: z.string(),
  currentPassword: z.string(),
  revokeOtherSessions: z.boolean().optional(),
})

/**
 * Password successfully changed
 */
export const zOpenapiChangePasswordResponse = z.object({
  token: z.string().optional(),
  user: z.object({
    id: z.string(),
    email: z.email(),
    name: z.string(),
    image: z.url().optional(),
    emailVerified: z.boolean(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
  }),
})

export const zOpenapiUpdateSessionBody = z.record(z.string(), z.unknown())

/**
 * Success
 */
export const zOpenapiUpdateSessionResponse = z.object({
  session: zOpenapiSession.optional(),
})

export const zOpenapiUpdateUserBody = z.object({
  name: z.string().optional(),
  image: z.string().optional(),
})

/**
 * Success
 */
export const zOpenapiUpdateUserResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiDeleteUserBody = z.object({
  callbackURL: z.string().optional(),
  password: z.string().optional(),
  token: z.string().optional(),
})

/**
 * User deletion processed successfully
 */
export const zOpenapiDeleteUserResponse = z.object({
  success: z.boolean(),
  message: z.enum(["User deleted", "Verification email sent"]),
})

export const zOpenapiRequestPasswordResetBody = z.object({
  email: z.string(),
  redirectTo: z.string().optional(),
})

/**
 * Success
 */
export const zOpenapiRequestPasswordResetResponse = z.object({
  status: z.boolean().optional(),
  message: z.string().optional(),
})

export const zOpenapiResetPasswordCallbackPath = z.object({
  token: z.string(),
})

export const zOpenapiResetPasswordCallbackQuery = z.object({
  callbackURL: z.string(),
})

/**
 * Success
 */
export const zOpenapiResetPasswordCallbackResponse = z.object({
  token: z.string().optional(),
})

/**
 * Success
 */
export const zOpenapiListUserSessionsResponse = z.array(zOpenapiSession)

export const zPostApiAuthRevokeSessionBody = z.object({
  token: z.string(),
})

/**
 * Success
 */
export const zPostApiAuthRevokeSessionResponse = z.object({
  status: z.boolean(),
})

export const zPostApiAuthRevokeSessionsBody = z.record(z.string(), z.unknown())

/**
 * Success
 */
export const zPostApiAuthRevokeSessionsResponse = z.object({
  status: z.boolean(),
})

export const zPostApiAuthRevokeOtherSessionsBody = z.record(
  z.string(),
  z.unknown()
)

/**
 * Success
 */
export const zPostApiAuthRevokeOtherSessionsResponse = z.object({
  status: z.boolean(),
})

export const zOpenapiLinkSocialAccountBody = z.object({
  callbackURL: z.string().optional(),
  provider: z.union([
    z.enum([
      "apple",
      "atlassian",
      "cognito",
      "discord",
      "facebook",
      "figma",
      "github",
      "microsoft",
      "google",
      "huggingface",
      "slack",
      "spotify",
      "twitch",
      "twitter",
      "dropbox",
      "kick",
      "linear",
      "linkedin",
      "gitlab",
      "tiktok",
      "reddit",
      "roblox",
      "salesforce",
      "vk",
      "zoom",
      "notion",
      "kakao",
      "naver",
      "line",
      "paybin",
      "paypal",
      "polar",
      "railway",
      "vercel",
      "wechat",
    ]),
    z.string(),
  ]),
  idToken: z
    .object({
      token: z.string(),
      nonce: z.string().optional(),
      accessToken: z.string().optional(),
      refreshToken: z.string().optional(),
      scopes: z.array(z.string()).optional(),
    })
    .optional(),
  requestSignUp: z.boolean().optional(),
  scopes: z.array(z.string()).optional(),
  errorCallbackURL: z.string().optional(),
  disableRedirect: z.boolean().optional(),
  additionalData: z.record(z.string(), z.unknown()).optional(),
})

/**
 * Success
 */
export const zOpenapiLinkSocialAccountResponse = z.object({
  url: z.string().optional(),
  redirect: z.boolean(),
  status: z.boolean().optional(),
})

/**
 * Success
 */
export const zOpenapiListUserAccountsResponse = z.array(
  z.object({
    id: z.string(),
    providerId: z.string(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    accountId: z.string(),
    userId: z.string(),
    scopes: z.array(z.string()),
  })
)

export const zGetApiAuthDeleteUserCallbackQuery = z.object({
  token: z.string().optional(),
  callbackURL: z.string().optional(),
})

/**
 * User successfully deleted
 */
export const zGetApiAuthDeleteUserCallbackResponse = z.object({
  success: z.boolean(),
  message: z.enum(["User deleted"]),
})

export const zPostApiAuthUnlinkAccountBody = z.object({
  providerId: z.string(),
  accountId: z.string().optional(),
})

/**
 * Success
 */
export const zPostApiAuthUnlinkAccountResponse = z.object({
  status: z.boolean().optional(),
})

export const zPostApiAuthRefreshTokenBody = z.object({
  providerId: z.string(),
  accountId: z.string().optional(),
  userId: z.string().optional(),
})

/**
 * Access token refreshed successfully
 */
export const zPostApiAuthRefreshTokenResponse = z.object({
  tokenType: z.string().optional(),
  idToken: z.string().optional(),
  accessToken: z.string().optional(),
  refreshToken: z.string().optional(),
  accessTokenExpiresAt: z.iso.datetime().optional(),
  refreshTokenExpiresAt: z.iso.datetime().optional(),
})

export const zPostApiAuthGetAccessTokenBody = z.object({
  providerId: z.string(),
  accountId: z.string().optional(),
  userId: z.string().optional(),
})

/**
 * A Valid access token
 */
export const zPostApiAuthGetAccessTokenResponse = z.object({
  tokenType: z.string().optional(),
  idToken: z.string().optional(),
  accessToken: z.string().optional(),
  accessTokenExpiresAt: z.iso.datetime().optional(),
})

/**
 * Success
 */
export const zGetApiAuthAccountInfoResponse = z.object({
  user: z.object({
    id: z.string(),
    name: z.string().optional(),
    email: z.string().optional(),
    image: z.string().optional(),
    emailVerified: z.boolean(),
  }),
  data: z.record(z.string(), z.unknown()),
})

/**
 * API is working
 */
export const zGetApiAuthOkResponse = z.object({
  ok: z.boolean(),
})

/**
 * The HTML content of the error page
 */
export const zGetApiAuthErrorResponse = z.string()

export const zOpenapiSetUserRoleBody = z.object({
  userId: z.string(),
  role: z.union([z.string(), z.array(z.string())]),
})

/**
 * User role updated
 */
export const zOpenapiSetUserRoleResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiGetUserQuery = z.object({
  id: z.string().optional(),
})

/**
 * User
 */
export const zOpenapiGetUserResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiCreateUserBody = z.object({
  email: z.string(),
  password: z.string().optional(),
  name: z.string(),
  role: z.union([z.string(), z.array(z.string())]).optional(),
  data: z.record(z.string(), z.unknown()).optional(),
})

/**
 * User created
 */
export const zOpenapiCreateUserResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiAdminUpdateUserBody = z.object({
  userId: z.string(),
  data: z.record(z.string(), z.unknown()),
})

/**
 * User updated
 */
export const zOpenapiAdminUpdateUserResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiListUsersQuery = z.object({
  searchValue: z.string().optional(),
  searchField: z.enum(["email", "name"]).optional(),
  searchOperator: z.enum(["contains", "starts_with", "ends_with"]).optional(),
  limit: z.union([z.string(), z.number()]).optional(),
  offset: z.union([z.string(), z.number()]).optional(),
  sortBy: z.string().optional(),
  sortDirection: z.enum(["asc", "desc"]).optional(),
  filterField: z.string().optional(),
  filterValue: z
    .union([
      z.union([
        z.union([z.union([z.string(), z.number()]), z.boolean()]),
        z.array(z.string()),
      ]),
      z.array(z.number()),
    ])
    .optional(),
  filterOperator: z
    .enum([
      "eq",
      "ne",
      "lt",
      "lte",
      "gt",
      "gte",
      "in",
      "not_in",
      "contains",
      "starts_with",
      "ends_with",
    ])
    .optional(),
})

/**
 * List of users
 */
export const zOpenapiListUsersResponse = z.object({
  users: z.array(zOpenapiUser),
  total: z.number(),
  limit: z.number().optional(),
  offset: z.number().optional(),
})

export const zOpenapiAdminListUserSessionsBody = z.object({
  userId: z.string(),
})

/**
 * List of user sessions
 */
export const zOpenapiAdminListUserSessionsResponse = z.object({
  sessions: z.array(zOpenapiSession).optional(),
})

export const zOpenapiUnbanUserBody = z.object({
  userId: z.string(),
})

/**
 * User unbanned
 */
export const zOpenapiUnbanUserResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiBanUserBody = z.object({
  userId: z.string(),
  banReason: z.string().optional(),
  banExpiresIn: z.number().optional(),
})

/**
 * User banned
 */
export const zOpenapiBanUserResponse = z.object({
  user: zOpenapiUser.optional(),
})

export const zOpenapiImpersonateUserBody = z.object({
  userId: z.string(),
})

/**
 * Impersonation session created
 */
export const zOpenapiImpersonateUserResponse = z.object({
  session: zOpenapiSession.optional(),
  user: zOpenapiUser.optional(),
})

export const zOpenapiRevokeUserSessionBody = z.object({
  sessionToken: z.string(),
})

/**
 * Session revoked
 */
export const zOpenapiRevokeUserSessionResponse = z.object({
  success: z.boolean().optional(),
})

export const zOpenapiRevokeUserSessionsBody = z.object({
  userId: z.string(),
})

/**
 * Sessions revoked
 */
export const zOpenapiRevokeUserSessionsResponse = z.object({
  success: z.boolean().optional(),
})

export const zOpenapiRemoveUserBody = z.object({
  userId: z.string(),
})

/**
 * User removed
 */
export const zOpenapiRemoveUserResponse = z.object({
  success: z.boolean().optional(),
})

export const zOpenapiSetUserPasswordBody = z.object({
  newPassword: z.string().min(1),
  userId: z.string().min(1),
})

/**
 * Password set
 */
export const zOpenapiSetUserPasswordResponse = z.object({
  status: z.boolean().optional(),
})

export const zPostApiAuthAdminHasPermissionBody = z.object({
  permissions: z.record(z.string(), z.unknown()),
})

/**
 * Success
 */
export const zPostApiAuthAdminHasPermissionResponse = z.object({
  error: z.string().optional(),
  success: z.boolean(),
})

/**
 * JSON Web Key Set retrieved successfully
 */
export const zOpenapiGetJsonWebKeySetResponse = z.object({
  keys: z.array(
    z.object({
      kid: z.string(),
      kty: z.string(),
      alg: z.string(),
      use: z.enum(["sig"]).optional(),
      n: z.string().optional(),
      e: z.string().optional(),
      crv: z.string().optional(),
      x: z.string().optional(),
      y: z.string().optional(),
    })
  ),
})

/**
 * Success
 */
export const zOpenapiGetJsonWebTokenResponse = z.object({
  token: z.string().optional(),
})

export const zGetApiBreedQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  search: z.string().optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
  speciesId: z
    .array(
      z
        .uuid()
        .regex(
          /[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/
        )
    )
    .optional(),
})

/**
 * OK
 */
export const zGetApiBreedResponse = zOpenapiPageResponseBreedDto

export const zPostApiBreedBody = zOpenapiCreateBreedRequest

/**
 * OK
 */
export const zPostApiBreedResponse = zOpenapiDataResponseBreedDto

export const zDeleteApiBreedByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiBreedByIdResponse = z.void()

export const zGetApiBreedByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiBreedByIdResponse = zOpenapiDataResponseBreedDto

export const zPutApiBreedByIdBody = zOpenapiUpdateBreedRequest

export const zPutApiBreedByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiBreedByIdResponse = zOpenapiDataResponseBreedDto

export const zGetApiClientQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  search: z.string().optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiClientResponse = zOpenapiPageResponseClientDto

export const zPostApiClientBody = zOpenapiCreateClientRequest

/**
 * OK
 */
export const zPostApiClientResponse = zOpenapiDataResponseClientDto

export const zDeleteApiClientByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiClientByIdResponse = z.void()

export const zGetApiClientByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiClientByIdResponse = zOpenapiDataResponseClientDto

export const zPutApiClientByIdBody = zOpenapiUpdateClientRequest

export const zPutApiClientByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiClientByIdResponse = zOpenapiDataResponseClientDto

export const zGetApiPatientQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  search: z.string().optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiPatientResponse = zOpenapiPageResponsePatientDto

export const zPostApiPatientBody = zOpenapiCreatePatientRequest

/**
 * OK
 */
export const zPostApiPatientResponse = zOpenapiDataResponsePatientDto

/**
 * OK
 */
export const zGetApiPatientStatsResponse = zOpenapiDataResponsePatientStatsDto

export const zDeleteApiPatientByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiPatientByIdResponse = z.void()

export const zGetApiPatientByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiPatientByIdResponse = zOpenapiDataResponsePatientDto

export const zPutApiPatientByIdBody = zOpenapiUpdatePatientRequest

export const zPutApiPatientByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiPatientByIdResponse = zOpenapiDataResponsePatientDto

export const zGetApiSpeciesQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  search: z.string().optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiSpeciesResponse = zOpenapiPageResponseSpeciesDto

export const zPostApiSpeciesBody = zOpenapiCreateSpeciesRequest

/**
 * OK
 */
export const zPostApiSpeciesResponse = zOpenapiDataResponseSpeciesDto

export const zDeleteApiSpeciesByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiSpeciesByIdResponse = z.void()

export const zGetApiSpeciesByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiSpeciesByIdResponse = zOpenapiDataResponseSpeciesDto

export const zPutApiSpeciesByIdBody = zOpenapiUpdateSpeciesRequest

export const zPutApiSpeciesByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiSpeciesByIdResponse = zOpenapiDataResponseSpeciesDto

export const zGetApiClinicalConditionQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  patientId: zOpenapiUuid.optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiClinicalConditionResponse =
  zOpenapiPageResponseMedicalConditionDto

export const zPostApiClinicalConditionBody =
  zOpenapiCreateMedicalConditionRequest

/**
 * OK
 */
export const zPostApiClinicalConditionResponse =
  zOpenapiDataResponseMedicalConditionDto

export const zDeleteApiClinicalConditionByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiClinicalConditionByIdResponse = z.void()

export const zGetApiClinicalConditionByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiClinicalConditionByIdResponse =
  zOpenapiDataResponseMedicalConditionDto

export const zPutApiClinicalConditionByIdBody =
  zOpenapiUpdateMedicalConditionRequest

export const zPutApiClinicalConditionByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiClinicalConditionByIdResponse =
  zOpenapiDataResponseMedicalConditionDto

export const zGetApiClinicalImmunizationQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  patientId: zOpenapiUuid.optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiClinicalImmunizationResponse =
  zOpenapiPageResponseImmunizationDto

export const zPostApiClinicalImmunizationBody =
  zOpenapiCreateImmunizationRequest

/**
 * OK
 */
export const zPostApiClinicalImmunizationResponse =
  zOpenapiDataResponseImmunizationDto

export const zDeleteApiClinicalImmunizationByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiClinicalImmunizationByIdResponse = z.void()

export const zGetApiClinicalImmunizationByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiClinicalImmunizationByIdResponse =
  zOpenapiDataResponseImmunizationDto

export const zPutApiClinicalImmunizationByIdBody =
  zOpenapiUpdateImmunizationRequest

export const zPutApiClinicalImmunizationByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiClinicalImmunizationByIdResponse =
  zOpenapiDataResponseImmunizationDto

export const zGetApiClinicalObservationQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  patientId: zOpenapiUuid.optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiClinicalObservationResponse =
  zOpenapiPageResponseMedicalObservationDto

export const zPostApiClinicalObservationBody =
  zOpenapiCreateMedicalObservationRequest

/**
 * OK
 */
export const zPostApiClinicalObservationResponse =
  zOpenapiDataResponseMedicalObservationDto

export const zDeleteApiClinicalObservationByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiClinicalObservationByIdResponse = z.void()

export const zGetApiClinicalObservationByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiClinicalObservationByIdResponse =
  zOpenapiDataResponseMedicalObservationDto

export const zPutApiClinicalObservationByIdBody =
  zOpenapiUpdateMedicalObservationRequest

export const zPutApiClinicalObservationByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiClinicalObservationByIdResponse =
  zOpenapiDataResponseMedicalObservationDto

export const zGetApiClinicalPrescriptionQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  patientId: zOpenapiUuid.optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiClinicalPrescriptionResponse =
  zOpenapiPageResponsePrescriptionDto

export const zPostApiClinicalPrescriptionBody =
  zOpenapiCreatePrescriptionRequest

/**
 * OK
 */
export const zPostApiClinicalPrescriptionResponse =
  zOpenapiDataResponsePrescriptionDto

export const zDeleteApiClinicalPrescriptionByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiClinicalPrescriptionByIdResponse = z.void()

export const zGetApiClinicalPrescriptionByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiClinicalPrescriptionByIdResponse =
  zOpenapiDataResponsePrescriptionDto

export const zPutApiClinicalPrescriptionByIdBody =
  zOpenapiUpdatePrescriptionRequest

export const zPutApiClinicalPrescriptionByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiClinicalPrescriptionByIdResponse =
  zOpenapiDataResponsePrescriptionDto

export const zGetApiClinicalProcedureQuery = z.object({
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  patientId: zOpenapiUuid.optional(),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
})

/**
 * OK
 */
export const zGetApiClinicalProcedureResponse = zOpenapiPageResponseProcedureDto

export const zPostApiClinicalProcedureBody = zOpenapiCreateProcedureRequest

/**
 * OK
 */
export const zPostApiClinicalProcedureResponse =
  zOpenapiDataResponseProcedureDto

export const zDeleteApiClinicalProcedureByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiClinicalProcedureByIdResponse = z.void()

export const zGetApiClinicalProcedureByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiClinicalProcedureByIdResponse =
  zOpenapiDataResponseProcedureDto

export const zPutApiClinicalProcedureByIdBody = zOpenapiUpdateProcedureRequest

export const zPutApiClinicalProcedureByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiClinicalProcedureByIdResponse =
  zOpenapiDataResponseProcedureDto

export const zGetApiAppointmentQuery = z.object({
  from: zOpenapiLocalDate.optional(),
  page: z
    .int()
    .gte(0)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(0),
  size: z
    .int()
    .gte(1)
    .max(2147483647, {
      error: "Invalid value: Expected int32 to be <= 2147483647",
    })
    .optional()
    .default(20),
  to: zOpenapiLocalDate.optional(),
})

/**
 * OK
 */
export const zGetApiAppointmentResponse = zOpenapiPageResponseAppointmentDto

export const zPostApiAppointmentBody = zOpenapiCreateAppointmentRequest

/**
 * OK
 */
export const zPostApiAppointmentResponse = zOpenapiDataResponseAppointmentDto

/**
 * OK
 */
export const zGetApiAppointmentEventsResponse = zOpenapiAppointmentEvent

/**
 * OK
 */
export const zGetApiAppointmentStatsResponse =
  zOpenapiDataResponseAppointmentStatsDto

export const zDeleteApiAppointmentByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * No Content
 */
export const zDeleteApiAppointmentByIdResponse = z.void()

export const zGetApiAppointmentByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zGetApiAppointmentByIdResponse = zOpenapiDataResponseAppointmentDto

export const zPutApiAppointmentByIdBody = zOpenapiUpdateAppointmentRequest

export const zPutApiAppointmentByIdPath = z.object({
  id: zOpenapiUuid,
})

/**
 * OK
 */
export const zPutApiAppointmentByIdResponse = zOpenapiDataResponseAppointmentDto
