export type {
  OpenapiCreateImmunizationRequest as CreateImmunizationRequest,
  OpenapiCreateMedicalObservationRequest as CreateObservationRequest,
  OpenapiCreatePrescriptionItemRequest as CreatePrescriptionItemRequest,
  OpenapiCreatePrescriptionRequest as CreatePrescriptionRequest,
  OpenapiCreateProcedureRequest as CreateProcedureRequest,
  OpenapiImmunizationDto as ImmunizationDto,
  OpenapiMedicalObservationDto as ObservationDto,
  OpenapiImmunizationRoute,
  OpenapiImmunizationStatus,
  OpenapiObservationCategory,
  OpenapiObservationStatus,
  OpenapiPrescriptionStatus,
  OpenapiProcedureCategory,
  OpenapiProcedureStatus,
  OpenapiPrescriptionDto as PrescriptionDto,
  OpenapiPrescriptionItemDto as PrescriptionItemDto,
  OpenapiProcedureDto as ProcedureDto,
  OpenapiUpdateImmunizationRequest as UpdateImmunizationRequest,
  OpenapiUpdateMedicalObservationRequest as UpdateObservationRequest,
  OpenapiUpdatePrescriptionItemRequest as UpdatePrescriptionItemRequest,
  OpenapiUpdatePrescriptionRequest as UpdatePrescriptionRequest,
  OpenapiUpdateProcedureRequest as UpdateProcedureRequest,
} from "@sanipatitas/shared/api/client/types.gen"
