export type {
  OpenapiMedicalObservationDto as ObservationDto,
  OpenapiCreateMedicalObservationRequest as CreateObservationRequest,
  OpenapiUpdateMedicalObservationRequest as UpdateObservationRequest,
  OpenapiObservationCategory,
  OpenapiObservationStatus,
  OpenapiImmunizationDto as ImmunizationDto,
  OpenapiCreateImmunizationRequest as CreateImmunizationRequest,
  OpenapiUpdateImmunizationRequest as UpdateImmunizationRequest,
  OpenapiImmunizationRoute,
  OpenapiImmunizationStatus,
  OpenapiProcedureDto as ProcedureDto,
  OpenapiCreateProcedureRequest as CreateProcedureRequest,
  OpenapiUpdateProcedureRequest as UpdateProcedureRequest,
  OpenapiProcedureCategory,
  OpenapiProcedureStatus,
  OpenapiPrescriptionDto as PrescriptionDto,
  OpenapiPrescriptionItemDto as PrescriptionItemDto,
  OpenapiCreatePrescriptionRequest as CreatePrescriptionRequest,
  OpenapiCreatePrescriptionItemRequest as CreatePrescriptionItemRequest,
  OpenapiUpdatePrescriptionRequest as UpdatePrescriptionRequest,
  OpenapiUpdatePrescriptionItemRequest as UpdatePrescriptionItemRequest,
  OpenapiPrescriptionStatus,
} from "@sanipatitas/shared/api/client/types.gen"
