// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  deleteApiAppointmentById,
  deleteApiBreedById,
  deleteApiClientById,
  deleteApiPatientById,
  deleteApiSpeciesById,
  getApiAppointment,
  getApiAppointmentById,
  getApiAuthAccountInfo,
  getApiAuthCallbackById,
  getApiAuthDeleteUserCallback,
  getApiAuthError,
  getApiAuthOk,
  getApiAuthVerifyEmail,
  getApiBreed,
  getApiBreedById,
  getApiClient,
  getApiClientById,
  getApiPatient,
  getApiPatientById,
  getApiSpecies,
  getApiSpeciesById,
  openapiAdminListUserSessions,
  openapiAdminUpdateUser,
  openapiBanUser,
  openapiChangeEmail,
  openapiChangePassword,
  openapiCreateUser,
  openapiDeleteUser,
  openapiGetJsonWebKeySet,
  openapiGetJsonWebToken,
  openapiGetSession,
  openapiGetSessionPost,
  openapiGetUser,
  openapiImpersonateUser,
  openapiLinkSocialAccount,
  openapiListUserAccounts,
  openapiListUsers,
  openapiListUserSessions,
  openapiRemoveUser,
  openapiRequestPasswordReset,
  openapiResetPassword,
  openapiResetPasswordCallback,
  openapiRevokeUserSession,
  openapiRevokeUserSessions,
  openapiSendVerificationEmail,
  openapiSetUserPassword,
  openapiSetUserRole,
  openapiSignInEmail,
  openapiSignOut,
  openapiSignUpWithEmailAndPassword,
  openapiSocialSignIn,
  openapiUnbanUser,
  openapiUpdateSession,
  openapiUpdateUser,
  openapiVerifyPassword,
  type Options,
  postApiAppointment,
  postApiAuthAdminHasPermission,
  postApiAuthAdminStopImpersonating,
  postApiAuthCallbackById,
  postApiAuthGetAccessToken,
  postApiAuthRefreshToken,
  postApiAuthRevokeOtherSessions,
  postApiAuthRevokeSession,
  postApiAuthRevokeSessions,
  postApiAuthUnlinkAccount,
  postApiBreed,
  postApiClient,
  postApiPatient,
  postApiSpecies,
  putApiAppointmentById,
  putApiBreedById,
  putApiClientById,
  putApiPatientById,
  putApiSpeciesById,
} from "../sdk.gen"
import type {
  DeleteApiAppointmentByIdData,
  DeleteApiAppointmentByIdError,
  DeleteApiAppointmentByIdResponse,
  DeleteApiBreedByIdData,
  DeleteApiBreedByIdError,
  DeleteApiBreedByIdResponse,
  DeleteApiClientByIdData,
  DeleteApiClientByIdError,
  DeleteApiClientByIdResponse,
  DeleteApiPatientByIdData,
  DeleteApiPatientByIdError,
  DeleteApiPatientByIdResponse,
  DeleteApiSpeciesByIdData,
  DeleteApiSpeciesByIdError,
  DeleteApiSpeciesByIdResponse,
  GetApiAppointmentByIdData,
  GetApiAppointmentByIdError,
  GetApiAppointmentByIdResponse,
  GetApiAppointmentData,
  GetApiAppointmentError,
  GetApiAppointmentResponse,
  GetApiAuthAccountInfoData,
  GetApiAuthAccountInfoError,
  GetApiAuthAccountInfoResponse,
  GetApiAuthCallbackByIdData,
  GetApiAuthCallbackByIdError,
  GetApiAuthDeleteUserCallbackData,
  GetApiAuthDeleteUserCallbackError,
  GetApiAuthDeleteUserCallbackResponse,
  GetApiAuthErrorData,
  GetApiAuthErrorError,
  GetApiAuthErrorResponse,
  GetApiAuthOkData,
  GetApiAuthOkError,
  GetApiAuthOkResponse,
  GetApiAuthVerifyEmailData,
  GetApiAuthVerifyEmailError,
  GetApiAuthVerifyEmailResponse,
  GetApiBreedByIdData,
  GetApiBreedByIdError,
  GetApiBreedByIdResponse,
  GetApiBreedData,
  GetApiBreedError,
  GetApiBreedResponse,
  GetApiClientByIdData,
  GetApiClientByIdError,
  GetApiClientByIdResponse,
  GetApiClientData,
  GetApiClientError,
  GetApiClientResponse,
  GetApiPatientByIdData,
  GetApiPatientByIdError,
  GetApiPatientByIdResponse,
  GetApiPatientData,
  GetApiPatientError,
  GetApiPatientResponse,
  GetApiSpeciesByIdData,
  GetApiSpeciesByIdError,
  GetApiSpeciesByIdResponse,
  GetApiSpeciesData,
  GetApiSpeciesError,
  GetApiSpeciesResponse,
  OpenapiAdminListUserSessionsData,
  OpenapiAdminListUserSessionsError,
  OpenapiAdminListUserSessionsResponse,
  OpenapiAdminUpdateUserData,
  OpenapiAdminUpdateUserError,
  OpenapiAdminUpdateUserResponse,
  OpenapiBanUserData,
  OpenapiBanUserError,
  OpenapiBanUserResponse,
  OpenapiChangeEmailData,
  OpenapiChangeEmailError,
  OpenapiChangeEmailResponse,
  OpenapiChangePasswordData,
  OpenapiChangePasswordError,
  OpenapiChangePasswordResponse,
  OpenapiCreateUserData,
  OpenapiCreateUserError,
  OpenapiCreateUserResponse,
  OpenapiDeleteUserData,
  OpenapiDeleteUserError,
  OpenapiDeleteUserResponse,
  OpenapiGetJsonWebKeySetData,
  OpenapiGetJsonWebKeySetError,
  OpenapiGetJsonWebKeySetResponse,
  OpenapiGetJsonWebTokenData,
  OpenapiGetJsonWebTokenError,
  OpenapiGetJsonWebTokenResponse,
  OpenapiGetSessionData,
  OpenapiGetSessionError,
  OpenapiGetSessionPostData,
  OpenapiGetSessionPostError,
  OpenapiGetSessionPostResponse,
  OpenapiGetSessionResponse,
  OpenapiGetUserData,
  OpenapiGetUserError,
  OpenapiGetUserResponse,
  OpenapiImpersonateUserData,
  OpenapiImpersonateUserError,
  OpenapiImpersonateUserResponse,
  OpenapiLinkSocialAccountData,
  OpenapiLinkSocialAccountError,
  OpenapiLinkSocialAccountResponse,
  OpenapiListUserAccountsData,
  OpenapiListUserAccountsError,
  OpenapiListUserAccountsResponse,
  OpenapiListUsersData,
  OpenapiListUsersError,
  OpenapiListUserSessionsData,
  OpenapiListUserSessionsError,
  OpenapiListUserSessionsResponse,
  OpenapiListUsersResponse,
  OpenapiRemoveUserData,
  OpenapiRemoveUserError,
  OpenapiRemoveUserResponse,
  OpenapiRequestPasswordResetData,
  OpenapiRequestPasswordResetError,
  OpenapiRequestPasswordResetResponse,
  OpenapiResetPasswordCallbackData,
  OpenapiResetPasswordCallbackError,
  OpenapiResetPasswordCallbackResponse,
  OpenapiResetPasswordData,
  OpenapiResetPasswordError,
  OpenapiResetPasswordResponse,
  OpenapiRevokeUserSessionData,
  OpenapiRevokeUserSessionError,
  OpenapiRevokeUserSessionResponse,
  OpenapiRevokeUserSessionsData,
  OpenapiRevokeUserSessionsError,
  OpenapiRevokeUserSessionsResponse,
  OpenapiSendVerificationEmailData,
  OpenapiSendVerificationEmailError,
  OpenapiSendVerificationEmailResponse,
  OpenapiSetUserPasswordData,
  OpenapiSetUserPasswordError,
  OpenapiSetUserPasswordResponse,
  OpenapiSetUserRoleData,
  OpenapiSetUserRoleError,
  OpenapiSetUserRoleResponse,
  OpenapiSignInEmailData,
  OpenapiSignInEmailError,
  OpenapiSignInEmailResponse,
  OpenapiSignOutData,
  OpenapiSignOutError,
  OpenapiSignOutResponse,
  OpenapiSignUpWithEmailAndPasswordData,
  OpenapiSignUpWithEmailAndPasswordError,
  OpenapiSignUpWithEmailAndPasswordResponse,
  OpenapiSocialSignInData,
  OpenapiSocialSignInError,
  OpenapiSocialSignInResponse,
  OpenapiUnbanUserData,
  OpenapiUnbanUserError,
  OpenapiUnbanUserResponse,
  OpenapiUpdateSessionData,
  OpenapiUpdateSessionError,
  OpenapiUpdateSessionResponse,
  OpenapiUpdateUserData,
  OpenapiUpdateUserError,
  OpenapiUpdateUserResponse,
  OpenapiVerifyPasswordData,
  OpenapiVerifyPasswordError,
  OpenapiVerifyPasswordResponse,
  PostApiAppointmentData,
  PostApiAppointmentError,
  PostApiAppointmentResponse,
  PostApiAuthAdminHasPermissionData,
  PostApiAuthAdminHasPermissionError,
  PostApiAuthAdminHasPermissionResponse,
  PostApiAuthAdminStopImpersonatingData,
  PostApiAuthAdminStopImpersonatingError,
  PostApiAuthCallbackByIdData,
  PostApiAuthCallbackByIdError,
  PostApiAuthGetAccessTokenData,
  PostApiAuthGetAccessTokenError,
  PostApiAuthGetAccessTokenResponse,
  PostApiAuthRefreshTokenData,
  PostApiAuthRefreshTokenError,
  PostApiAuthRefreshTokenResponse,
  PostApiAuthRevokeOtherSessionsData,
  PostApiAuthRevokeOtherSessionsError,
  PostApiAuthRevokeOtherSessionsResponse,
  PostApiAuthRevokeSessionData,
  PostApiAuthRevokeSessionError,
  PostApiAuthRevokeSessionResponse,
  PostApiAuthRevokeSessionsData,
  PostApiAuthRevokeSessionsError,
  PostApiAuthRevokeSessionsResponse,
  PostApiAuthUnlinkAccountData,
  PostApiAuthUnlinkAccountError,
  PostApiAuthUnlinkAccountResponse,
  PostApiBreedData,
  PostApiBreedError,
  PostApiBreedResponse,
  PostApiClientData,
  PostApiClientError,
  PostApiClientResponse,
  PostApiPatientData,
  PostApiPatientError,
  PostApiPatientResponse,
  PostApiSpeciesData,
  PostApiSpeciesError,
  PostApiSpeciesResponse,
  PutApiAppointmentByIdData,
  PutApiAppointmentByIdError,
  PutApiAppointmentByIdResponse,
  PutApiBreedByIdData,
  PutApiBreedByIdError,
  PutApiBreedByIdResponse,
  PutApiClientByIdData,
  PutApiClientByIdError,
  PutApiClientByIdResponse,
  PutApiPatientByIdData,
  PutApiPatientByIdError,
  PutApiPatientByIdResponse,
  PutApiSpeciesByIdData,
  PutApiSpeciesByIdError,
  PutApiSpeciesByIdResponse,
} from "../types.gen"

/**
 * Sign in with a social provider
 */
export const openapiSocialSignInMutation = (
  options?: Partial<Options<OpenapiSocialSignInData>>
): UseMutationOptions<
  OpenapiSocialSignInResponse,
  OpenapiSocialSignInError,
  Options<OpenapiSocialSignInData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSocialSignInResponse,
    OpenapiSocialSignInError,
    Options<OpenapiSocialSignInData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSocialSignIn({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getApiAuthCallbackByIdQueryKey = (
  options: Options<GetApiAuthCallbackByIdData>
) => createQueryKey("getApiAuthCallbackById", options)

export const getApiAuthCallbackByIdOptions = (
  options: Options<GetApiAuthCallbackByIdData>
) =>
  queryOptions<
    unknown,
    GetApiAuthCallbackByIdError,
    unknown,
    ReturnType<typeof getApiAuthCallbackByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthCallbackById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAuthCallbackByIdQueryKey(options),
  })

export const postApiAuthCallbackByIdMutation = (
  options?: Partial<Options<PostApiAuthCallbackByIdData>>
): UseMutationOptions<
  unknown,
  PostApiAuthCallbackByIdError,
  Options<PostApiAuthCallbackByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostApiAuthCallbackByIdError,
    Options<PostApiAuthCallbackByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthCallbackById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiGetSessionQueryKey = (
  options?: Options<OpenapiGetSessionData>
) => createQueryKey("openapiGetSession", options)

/**
 * Get the current session
 */
export const openapiGetSessionOptions = (
  options?: Options<OpenapiGetSessionData>
) =>
  queryOptions<
    OpenapiGetSessionResponse,
    OpenapiGetSessionError,
    OpenapiGetSessionResponse,
    ReturnType<typeof openapiGetSessionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiGetSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiGetSessionQueryKey(options),
  })

/**
 * Get the current session
 */
export const openapiGetSessionPostMutation = (
  options?: Partial<Options<OpenapiGetSessionPostData>>
): UseMutationOptions<
  OpenapiGetSessionPostResponse,
  OpenapiGetSessionPostError,
  Options<OpenapiGetSessionPostData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiGetSessionPostResponse,
    OpenapiGetSessionPostError,
    Options<OpenapiGetSessionPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiGetSessionPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Sign out the current user
 */
export const openapiSignOutMutation = (
  options?: Partial<Options<OpenapiSignOutData>>
): UseMutationOptions<
  OpenapiSignOutResponse,
  OpenapiSignOutError,
  Options<OpenapiSignOutData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSignOutResponse,
    OpenapiSignOutError,
    Options<OpenapiSignOutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSignOut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Sign up a user using email and password
 */
export const openapiSignUpWithEmailAndPasswordMutation = (
  options?: Partial<Options<OpenapiSignUpWithEmailAndPasswordData>>
): UseMutationOptions<
  OpenapiSignUpWithEmailAndPasswordResponse,
  OpenapiSignUpWithEmailAndPasswordError,
  Options<OpenapiSignUpWithEmailAndPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSignUpWithEmailAndPasswordResponse,
    OpenapiSignUpWithEmailAndPasswordError,
    Options<OpenapiSignUpWithEmailAndPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSignUpWithEmailAndPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Sign in with email and password
 */
export const openapiSignInEmailMutation = (
  options?: Partial<Options<OpenapiSignInEmailData>>
): UseMutationOptions<
  OpenapiSignInEmailResponse,
  OpenapiSignInEmailError,
  Options<OpenapiSignInEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSignInEmailResponse,
    OpenapiSignInEmailError,
    Options<OpenapiSignInEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSignInEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Reset the password for a user
 */
export const openapiResetPasswordMutation = (
  options?: Partial<Options<OpenapiResetPasswordData>>
): UseMutationOptions<
  OpenapiResetPasswordResponse,
  OpenapiResetPasswordError,
  Options<OpenapiResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiResetPasswordResponse,
    OpenapiResetPasswordError,
    Options<OpenapiResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Verify the current user's password
 */
export const openapiVerifyPasswordMutation = (
  options?: Partial<Options<OpenapiVerifyPasswordData>>
): UseMutationOptions<
  OpenapiVerifyPasswordResponse,
  OpenapiVerifyPasswordError,
  Options<OpenapiVerifyPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiVerifyPasswordResponse,
    OpenapiVerifyPasswordError,
    Options<OpenapiVerifyPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiVerifyPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAuthVerifyEmailQueryKey = (
  options: Options<GetApiAuthVerifyEmailData>
) => createQueryKey("getApiAuthVerifyEmail", options)

/**
 * Verify the email of the user
 */
export const getApiAuthVerifyEmailOptions = (
  options: Options<GetApiAuthVerifyEmailData>
) =>
  queryOptions<
    GetApiAuthVerifyEmailResponse,
    GetApiAuthVerifyEmailError,
    GetApiAuthVerifyEmailResponse,
    ReturnType<typeof getApiAuthVerifyEmailQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthVerifyEmail({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAuthVerifyEmailQueryKey(options),
  })

/**
 * Send a verification email to the user
 */
export const openapiSendVerificationEmailMutation = (
  options?: Partial<Options<OpenapiSendVerificationEmailData>>
): UseMutationOptions<
  OpenapiSendVerificationEmailResponse,
  OpenapiSendVerificationEmailError,
  Options<OpenapiSendVerificationEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSendVerificationEmailResponse,
    OpenapiSendVerificationEmailError,
    Options<OpenapiSendVerificationEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSendVerificationEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiChangeEmailMutation = (
  options?: Partial<Options<OpenapiChangeEmailData>>
): UseMutationOptions<
  OpenapiChangeEmailResponse,
  OpenapiChangeEmailError,
  Options<OpenapiChangeEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiChangeEmailResponse,
    OpenapiChangeEmailError,
    Options<OpenapiChangeEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiChangeEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Change the password of the user
 */
export const openapiChangePasswordMutation = (
  options?: Partial<Options<OpenapiChangePasswordData>>
): UseMutationOptions<
  OpenapiChangePasswordResponse,
  OpenapiChangePasswordError,
  Options<OpenapiChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiChangePasswordResponse,
    OpenapiChangePasswordError,
    Options<OpenapiChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update the current session
 */
export const openapiUpdateSessionMutation = (
  options?: Partial<Options<OpenapiUpdateSessionData>>
): UseMutationOptions<
  OpenapiUpdateSessionResponse,
  OpenapiUpdateSessionError,
  Options<OpenapiUpdateSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiUpdateSessionResponse,
    OpenapiUpdateSessionError,
    Options<OpenapiUpdateSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiUpdateSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update the current user
 */
export const openapiUpdateUserMutation = (
  options?: Partial<Options<OpenapiUpdateUserData>>
): UseMutationOptions<
  OpenapiUpdateUserResponse,
  OpenapiUpdateUserError,
  Options<OpenapiUpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiUpdateUserResponse,
    OpenapiUpdateUserError,
    Options<OpenapiUpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiUpdateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete the user
 */
export const openapiDeleteUserMutation = (
  options?: Partial<Options<OpenapiDeleteUserData>>
): UseMutationOptions<
  OpenapiDeleteUserResponse,
  OpenapiDeleteUserError,
  Options<OpenapiDeleteUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiDeleteUserResponse,
    OpenapiDeleteUserError,
    Options<OpenapiDeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiDeleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Send a password reset email to the user
 */
export const openapiRequestPasswordResetMutation = (
  options?: Partial<Options<OpenapiRequestPasswordResetData>>
): UseMutationOptions<
  OpenapiRequestPasswordResetResponse,
  OpenapiRequestPasswordResetError,
  Options<OpenapiRequestPasswordResetData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiRequestPasswordResetResponse,
    OpenapiRequestPasswordResetError,
    Options<OpenapiRequestPasswordResetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiRequestPasswordReset({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiResetPasswordCallbackQueryKey = (
  options: Options<OpenapiResetPasswordCallbackData>
) => createQueryKey("openapiResetPasswordCallback", options)

/**
 * Redirects the user to the callback URL with the token
 */
export const openapiResetPasswordCallbackOptions = (
  options: Options<OpenapiResetPasswordCallbackData>
) =>
  queryOptions<
    OpenapiResetPasswordCallbackResponse,
    OpenapiResetPasswordCallbackError,
    OpenapiResetPasswordCallbackResponse,
    ReturnType<typeof openapiResetPasswordCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiResetPasswordCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiResetPasswordCallbackQueryKey(options),
  })

export const openapiListUserSessionsQueryKey = (
  options?: Options<OpenapiListUserSessionsData>
) => createQueryKey("openapiListUserSessions", options)

/**
 * List all active sessions for the user
 */
export const openapiListUserSessionsOptions = (
  options?: Options<OpenapiListUserSessionsData>
) =>
  queryOptions<
    OpenapiListUserSessionsResponse,
    OpenapiListUserSessionsError,
    OpenapiListUserSessionsResponse,
    ReturnType<typeof openapiListUserSessionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiListUserSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiListUserSessionsQueryKey(options),
  })

/**
 * Revoke a single session
 */
export const postApiAuthRevokeSessionMutation = (
  options?: Partial<Options<PostApiAuthRevokeSessionData>>
): UseMutationOptions<
  PostApiAuthRevokeSessionResponse,
  PostApiAuthRevokeSessionError,
  Options<PostApiAuthRevokeSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthRevokeSessionResponse,
    PostApiAuthRevokeSessionError,
    Options<PostApiAuthRevokeSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthRevokeSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Revoke all sessions for the user
 */
export const postApiAuthRevokeSessionsMutation = (
  options?: Partial<Options<PostApiAuthRevokeSessionsData>>
): UseMutationOptions<
  PostApiAuthRevokeSessionsResponse,
  PostApiAuthRevokeSessionsError,
  Options<PostApiAuthRevokeSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthRevokeSessionsResponse,
    PostApiAuthRevokeSessionsError,
    Options<PostApiAuthRevokeSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthRevokeSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Revoke all other sessions for the user except the current one
 */
export const postApiAuthRevokeOtherSessionsMutation = (
  options?: Partial<Options<PostApiAuthRevokeOtherSessionsData>>
): UseMutationOptions<
  PostApiAuthRevokeOtherSessionsResponse,
  PostApiAuthRevokeOtherSessionsError,
  Options<PostApiAuthRevokeOtherSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthRevokeOtherSessionsResponse,
    PostApiAuthRevokeOtherSessionsError,
    Options<PostApiAuthRevokeOtherSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthRevokeOtherSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Link a social account to the user
 */
export const openapiLinkSocialAccountMutation = (
  options?: Partial<Options<OpenapiLinkSocialAccountData>>
): UseMutationOptions<
  OpenapiLinkSocialAccountResponse,
  OpenapiLinkSocialAccountError,
  Options<OpenapiLinkSocialAccountData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiLinkSocialAccountResponse,
    OpenapiLinkSocialAccountError,
    Options<OpenapiLinkSocialAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiLinkSocialAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiListUserAccountsQueryKey = (
  options?: Options<OpenapiListUserAccountsData>
) => createQueryKey("openapiListUserAccounts", options)

/**
 * List all accounts linked to the user
 */
export const openapiListUserAccountsOptions = (
  options?: Options<OpenapiListUserAccountsData>
) =>
  queryOptions<
    OpenapiListUserAccountsResponse,
    OpenapiListUserAccountsError,
    OpenapiListUserAccountsResponse,
    ReturnType<typeof openapiListUserAccountsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiListUserAccounts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiListUserAccountsQueryKey(options),
  })

export const getApiAuthDeleteUserCallbackQueryKey = (
  options?: Options<GetApiAuthDeleteUserCallbackData>
) => createQueryKey("getApiAuthDeleteUserCallback", options)

/**
 * Callback to complete user deletion with verification token
 */
export const getApiAuthDeleteUserCallbackOptions = (
  options?: Options<GetApiAuthDeleteUserCallbackData>
) =>
  queryOptions<
    GetApiAuthDeleteUserCallbackResponse,
    GetApiAuthDeleteUserCallbackError,
    GetApiAuthDeleteUserCallbackResponse,
    ReturnType<typeof getApiAuthDeleteUserCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthDeleteUserCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAuthDeleteUserCallbackQueryKey(options),
  })

/**
 * Unlink an account
 */
export const postApiAuthUnlinkAccountMutation = (
  options?: Partial<Options<PostApiAuthUnlinkAccountData>>
): UseMutationOptions<
  PostApiAuthUnlinkAccountResponse,
  PostApiAuthUnlinkAccountError,
  Options<PostApiAuthUnlinkAccountData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthUnlinkAccountResponse,
    PostApiAuthUnlinkAccountError,
    Options<PostApiAuthUnlinkAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthUnlinkAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Refresh the access token using a refresh token
 */
export const postApiAuthRefreshTokenMutation = (
  options?: Partial<Options<PostApiAuthRefreshTokenData>>
): UseMutationOptions<
  PostApiAuthRefreshTokenResponse,
  PostApiAuthRefreshTokenError,
  Options<PostApiAuthRefreshTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthRefreshTokenResponse,
    PostApiAuthRefreshTokenError,
    Options<PostApiAuthRefreshTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthRefreshToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postApiAuthGetAccessTokenMutation = (
  options?: Partial<Options<PostApiAuthGetAccessTokenData>>
): UseMutationOptions<
  PostApiAuthGetAccessTokenResponse,
  PostApiAuthGetAccessTokenError,
  Options<PostApiAuthGetAccessTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthGetAccessTokenResponse,
    PostApiAuthGetAccessTokenError,
    Options<PostApiAuthGetAccessTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthGetAccessToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAuthAccountInfoQueryKey = (
  options?: Options<GetApiAuthAccountInfoData>
) => createQueryKey("getApiAuthAccountInfo", options)

/**
 * Get the account info provided by the provider
 */
export const getApiAuthAccountInfoOptions = (
  options?: Options<GetApiAuthAccountInfoData>
) =>
  queryOptions<
    GetApiAuthAccountInfoResponse,
    GetApiAuthAccountInfoError,
    GetApiAuthAccountInfoResponse,
    ReturnType<typeof getApiAuthAccountInfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthAccountInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAuthAccountInfoQueryKey(options),
  })

export const getApiAuthOkQueryKey = (options?: Options<GetApiAuthOkData>) =>
  createQueryKey("getApiAuthOk", options)

/**
 * Check if the API is working
 */
export const getApiAuthOkOptions = (options?: Options<GetApiAuthOkData>) =>
  queryOptions<
    GetApiAuthOkResponse,
    GetApiAuthOkError,
    GetApiAuthOkResponse,
    ReturnType<typeof getApiAuthOkQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthOk({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAuthOkQueryKey(options),
  })

export const getApiAuthErrorQueryKey = (
  options?: Options<GetApiAuthErrorData>
) => createQueryKey("getApiAuthError", options)

/**
 * Displays an error page
 */
export const getApiAuthErrorOptions = (
  options?: Options<GetApiAuthErrorData>
) =>
  queryOptions<
    GetApiAuthErrorResponse,
    GetApiAuthErrorError,
    GetApiAuthErrorResponse,
    ReturnType<typeof getApiAuthErrorQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAuthError({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAuthErrorQueryKey(options),
  })

/**
 * Set the role of a user
 */
export const openapiSetUserRoleMutation = (
  options?: Partial<Options<OpenapiSetUserRoleData>>
): UseMutationOptions<
  OpenapiSetUserRoleResponse,
  OpenapiSetUserRoleError,
  Options<OpenapiSetUserRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSetUserRoleResponse,
    OpenapiSetUserRoleError,
    Options<OpenapiSetUserRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSetUserRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiGetUserQueryKey = (options?: Options<OpenapiGetUserData>) =>
  createQueryKey("openapiGetUser", options)

/**
 * Get an existing user
 */
export const openapiGetUserOptions = (options?: Options<OpenapiGetUserData>) =>
  queryOptions<
    OpenapiGetUserResponse,
    OpenapiGetUserError,
    OpenapiGetUserResponse,
    ReturnType<typeof openapiGetUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiGetUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiGetUserQueryKey(options),
  })

/**
 * Create a new user
 */
export const openapiCreateUserMutation = (
  options?: Partial<Options<OpenapiCreateUserData>>
): UseMutationOptions<
  OpenapiCreateUserResponse,
  OpenapiCreateUserError,
  Options<OpenapiCreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiCreateUserResponse,
    OpenapiCreateUserError,
    Options<OpenapiCreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiCreateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update a user's details
 */
export const openapiAdminUpdateUserMutation = (
  options?: Partial<Options<OpenapiAdminUpdateUserData>>
): UseMutationOptions<
  OpenapiAdminUpdateUserResponse,
  OpenapiAdminUpdateUserError,
  Options<OpenapiAdminUpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiAdminUpdateUserResponse,
    OpenapiAdminUpdateUserError,
    Options<OpenapiAdminUpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiAdminUpdateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiListUsersQueryKey = (
  options?: Options<OpenapiListUsersData>
) => createQueryKey("openapiListUsers", options)

/**
 * List users
 */
export const openapiListUsersOptions = (
  options?: Options<OpenapiListUsersData>
) =>
  queryOptions<
    OpenapiListUsersResponse,
    OpenapiListUsersError,
    OpenapiListUsersResponse,
    ReturnType<typeof openapiListUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiListUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiListUsersQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const openapiListUsersInfiniteQueryKey = (
  options?: Options<OpenapiListUsersData>
): QueryKey<Options<OpenapiListUsersData>> =>
  createQueryKey("openapiListUsers", options, true)

/**
 * List users
 */
export const openapiListUsersInfiniteOptions = (
  options?: Options<OpenapiListUsersData>
) => {
  const opts = infiniteQueryOptions<
    OpenapiListUsersResponse,
    OpenapiListUsersError,
    InfiniteData<OpenapiListUsersResponse>,
    QueryKey<Options<OpenapiListUsersData>>,
    | string
    | number
    | Pick<
        QueryKey<Options<OpenapiListUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<OpenapiListUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await openapiListUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: openapiListUsersInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * List user sessions
 */
export const openapiAdminListUserSessionsMutation = (
  options?: Partial<Options<OpenapiAdminListUserSessionsData>>
): UseMutationOptions<
  OpenapiAdminListUserSessionsResponse,
  OpenapiAdminListUserSessionsError,
  Options<OpenapiAdminListUserSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiAdminListUserSessionsResponse,
    OpenapiAdminListUserSessionsError,
    Options<OpenapiAdminListUserSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiAdminListUserSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Unban a user
 */
export const openapiUnbanUserMutation = (
  options?: Partial<Options<OpenapiUnbanUserData>>
): UseMutationOptions<
  OpenapiUnbanUserResponse,
  OpenapiUnbanUserError,
  Options<OpenapiUnbanUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiUnbanUserResponse,
    OpenapiUnbanUserError,
    Options<OpenapiUnbanUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiUnbanUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Ban a user
 */
export const openapiBanUserMutation = (
  options?: Partial<Options<OpenapiBanUserData>>
): UseMutationOptions<
  OpenapiBanUserResponse,
  OpenapiBanUserError,
  Options<OpenapiBanUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiBanUserResponse,
    OpenapiBanUserError,
    Options<OpenapiBanUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiBanUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Impersonate a user
 */
export const openapiImpersonateUserMutation = (
  options?: Partial<Options<OpenapiImpersonateUserData>>
): UseMutationOptions<
  OpenapiImpersonateUserResponse,
  OpenapiImpersonateUserError,
  Options<OpenapiImpersonateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiImpersonateUserResponse,
    OpenapiImpersonateUserError,
    Options<OpenapiImpersonateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiImpersonateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const postApiAuthAdminStopImpersonatingMutation = (
  options?: Partial<Options<PostApiAuthAdminStopImpersonatingData>>
): UseMutationOptions<
  unknown,
  PostApiAuthAdminStopImpersonatingError,
  Options<PostApiAuthAdminStopImpersonatingData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostApiAuthAdminStopImpersonatingError,
    Options<PostApiAuthAdminStopImpersonatingData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthAdminStopImpersonating({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Revoke a user session
 */
export const openapiRevokeUserSessionMutation = (
  options?: Partial<Options<OpenapiRevokeUserSessionData>>
): UseMutationOptions<
  OpenapiRevokeUserSessionResponse,
  OpenapiRevokeUserSessionError,
  Options<OpenapiRevokeUserSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiRevokeUserSessionResponse,
    OpenapiRevokeUserSessionError,
    Options<OpenapiRevokeUserSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiRevokeUserSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Revoke all user sessions
 */
export const openapiRevokeUserSessionsMutation = (
  options?: Partial<Options<OpenapiRevokeUserSessionsData>>
): UseMutationOptions<
  OpenapiRevokeUserSessionsResponse,
  OpenapiRevokeUserSessionsError,
  Options<OpenapiRevokeUserSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiRevokeUserSessionsResponse,
    OpenapiRevokeUserSessionsError,
    Options<OpenapiRevokeUserSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiRevokeUserSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete a user and all their sessions and accounts. Cannot be undone.
 */
export const openapiRemoveUserMutation = (
  options?: Partial<Options<OpenapiRemoveUserData>>
): UseMutationOptions<
  OpenapiRemoveUserResponse,
  OpenapiRemoveUserError,
  Options<OpenapiRemoveUserData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiRemoveUserResponse,
    OpenapiRemoveUserError,
    Options<OpenapiRemoveUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiRemoveUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Set a user's password
 */
export const openapiSetUserPasswordMutation = (
  options?: Partial<Options<OpenapiSetUserPasswordData>>
): UseMutationOptions<
  OpenapiSetUserPasswordResponse,
  OpenapiSetUserPasswordError,
  Options<OpenapiSetUserPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    OpenapiSetUserPasswordResponse,
    OpenapiSetUserPasswordError,
    Options<OpenapiSetUserPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await openapiSetUserPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Check if the user has permission
 */
export const postApiAuthAdminHasPermissionMutation = (
  options?: Partial<Options<PostApiAuthAdminHasPermissionData>>
): UseMutationOptions<
  PostApiAuthAdminHasPermissionResponse,
  PostApiAuthAdminHasPermissionError,
  Options<PostApiAuthAdminHasPermissionData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAuthAdminHasPermissionResponse,
    PostApiAuthAdminHasPermissionError,
    Options<PostApiAuthAdminHasPermissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAuthAdminHasPermission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const openapiGetJsonWebKeySetQueryKey = (
  options?: Options<OpenapiGetJsonWebKeySetData>
) => createQueryKey("openapiGetJsonWebKeySet", options)

/**
 * Get the JSON Web Key Set
 */
export const openapiGetJsonWebKeySetOptions = (
  options?: Options<OpenapiGetJsonWebKeySetData>
) =>
  queryOptions<
    OpenapiGetJsonWebKeySetResponse,
    OpenapiGetJsonWebKeySetError,
    OpenapiGetJsonWebKeySetResponse,
    ReturnType<typeof openapiGetJsonWebKeySetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiGetJsonWebKeySet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiGetJsonWebKeySetQueryKey(options),
  })

export const openapiGetJsonWebTokenQueryKey = (
  options?: Options<OpenapiGetJsonWebTokenData>
) => createQueryKey("openapiGetJsonWebToken", options)

/**
 * Get a JWT token
 */
export const openapiGetJsonWebTokenOptions = (
  options?: Options<OpenapiGetJsonWebTokenData>
) =>
  queryOptions<
    OpenapiGetJsonWebTokenResponse,
    OpenapiGetJsonWebTokenError,
    OpenapiGetJsonWebTokenResponse,
    ReturnType<typeof openapiGetJsonWebTokenQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await openapiGetJsonWebToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: openapiGetJsonWebTokenQueryKey(options),
  })

export const getApiBreedQueryKey = (options?: Options<GetApiBreedData>) =>
  createQueryKey("getApiBreed", options)

/**
 * Search
 */
export const getApiBreedOptions = (options?: Options<GetApiBreedData>) =>
  queryOptions<
    GetApiBreedResponse,
    GetApiBreedError,
    GetApiBreedResponse,
    ReturnType<typeof getApiBreedQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiBreed({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiBreedQueryKey(options),
  })

export const getApiBreedInfiniteQueryKey = (
  options?: Options<GetApiBreedData>
): QueryKey<Options<GetApiBreedData>> =>
  createQueryKey("getApiBreed", options, true)

/**
 * Search
 */
export const getApiBreedInfiniteOptions = (
  options?: Options<GetApiBreedData>
) => {
  const opts = infiniteQueryOptions<
    GetApiBreedResponse,
    GetApiBreedError,
    InfiniteData<GetApiBreedResponse>,
    QueryKey<Options<GetApiBreedData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiBreedData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiBreedData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiBreed({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiBreedInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Create
 */
export const postApiBreedMutation = (
  options?: Partial<Options<PostApiBreedData>>
): UseMutationOptions<
  PostApiBreedResponse,
  PostApiBreedError,
  Options<PostApiBreedData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiBreedResponse,
    PostApiBreedError,
    Options<PostApiBreedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiBreed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 */
export const deleteApiBreedByIdMutation = (
  options?: Partial<Options<DeleteApiBreedByIdData>>
): UseMutationOptions<
  DeleteApiBreedByIdResponse,
  DeleteApiBreedByIdError,
  Options<DeleteApiBreedByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiBreedByIdResponse,
    DeleteApiBreedByIdError,
    Options<DeleteApiBreedByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiBreedById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiBreedByIdQueryKey = (
  options: Options<GetApiBreedByIdData>
) => createQueryKey("getApiBreedById", options)

/**
 * Get By Id
 */
export const getApiBreedByIdOptions = (options: Options<GetApiBreedByIdData>) =>
  queryOptions<
    GetApiBreedByIdResponse,
    GetApiBreedByIdError,
    GetApiBreedByIdResponse,
    ReturnType<typeof getApiBreedByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiBreedById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiBreedByIdQueryKey(options),
  })

/**
 * Update
 */
export const putApiBreedByIdMutation = (
  options?: Partial<Options<PutApiBreedByIdData>>
): UseMutationOptions<
  PutApiBreedByIdResponse,
  PutApiBreedByIdError,
  Options<PutApiBreedByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiBreedByIdResponse,
    PutApiBreedByIdError,
    Options<PutApiBreedByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiBreedById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiClientQueryKey = (options?: Options<GetApiClientData>) =>
  createQueryKey("getApiClient", options)

/**
 * Search
 */
export const getApiClientOptions = (options?: Options<GetApiClientData>) =>
  queryOptions<
    GetApiClientResponse,
    GetApiClientError,
    GetApiClientResponse,
    ReturnType<typeof getApiClientQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClient({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiClientQueryKey(options),
  })

export const getApiClientInfiniteQueryKey = (
  options?: Options<GetApiClientData>
): QueryKey<Options<GetApiClientData>> =>
  createQueryKey("getApiClient", options, true)

/**
 * Search
 */
export const getApiClientInfiniteOptions = (
  options?: Options<GetApiClientData>
) => {
  const opts = infiniteQueryOptions<
    GetApiClientResponse,
    GetApiClientError,
    InfiniteData<GetApiClientResponse>,
    QueryKey<Options<GetApiClientData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiClientData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiClientData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiClient({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiClientInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Create
 */
export const postApiClientMutation = (
  options?: Partial<Options<PostApiClientData>>
): UseMutationOptions<
  PostApiClientResponse,
  PostApiClientError,
  Options<PostApiClientData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiClientResponse,
    PostApiClientError,
    Options<PostApiClientData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiClient({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 */
export const deleteApiClientByIdMutation = (
  options?: Partial<Options<DeleteApiClientByIdData>>
): UseMutationOptions<
  DeleteApiClientByIdResponse,
  DeleteApiClientByIdError,
  Options<DeleteApiClientByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiClientByIdResponse,
    DeleteApiClientByIdError,
    Options<DeleteApiClientByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiClientById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiClientByIdQueryKey = (
  options: Options<GetApiClientByIdData>
) => createQueryKey("getApiClientById", options)

/**
 * Get By Id
 */
export const getApiClientByIdOptions = (
  options: Options<GetApiClientByIdData>
) =>
  queryOptions<
    GetApiClientByIdResponse,
    GetApiClientByIdError,
    GetApiClientByIdResponse,
    ReturnType<typeof getApiClientByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiClientById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiClientByIdQueryKey(options),
  })

/**
 * Update
 */
export const putApiClientByIdMutation = (
  options?: Partial<Options<PutApiClientByIdData>>
): UseMutationOptions<
  PutApiClientByIdResponse,
  PutApiClientByIdError,
  Options<PutApiClientByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiClientByIdResponse,
    PutApiClientByIdError,
    Options<PutApiClientByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiClientById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPatientQueryKey = (options?: Options<GetApiPatientData>) =>
  createQueryKey("getApiPatient", options)

/**
 * Search
 */
export const getApiPatientOptions = (options?: Options<GetApiPatientData>) =>
  queryOptions<
    GetApiPatientResponse,
    GetApiPatientError,
    GetApiPatientResponse,
    ReturnType<typeof getApiPatientQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPatient({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPatientQueryKey(options),
  })

export const getApiPatientInfiniteQueryKey = (
  options?: Options<GetApiPatientData>
): QueryKey<Options<GetApiPatientData>> =>
  createQueryKey("getApiPatient", options, true)

/**
 * Search
 */
export const getApiPatientInfiniteOptions = (
  options?: Options<GetApiPatientData>
) => {
  const opts = infiniteQueryOptions<
    GetApiPatientResponse,
    GetApiPatientError,
    InfiniteData<GetApiPatientResponse>,
    QueryKey<Options<GetApiPatientData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiPatientData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiPatientData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiPatient({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiPatientInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Create
 */
export const postApiPatientMutation = (
  options?: Partial<Options<PostApiPatientData>>
): UseMutationOptions<
  PostApiPatientResponse,
  PostApiPatientError,
  Options<PostApiPatientData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiPatientResponse,
    PostApiPatientError,
    Options<PostApiPatientData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiPatient({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 */
export const deleteApiPatientByIdMutation = (
  options?: Partial<Options<DeleteApiPatientByIdData>>
): UseMutationOptions<
  DeleteApiPatientByIdResponse,
  DeleteApiPatientByIdError,
  Options<DeleteApiPatientByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiPatientByIdResponse,
    DeleteApiPatientByIdError,
    Options<DeleteApiPatientByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiPatientById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiPatientByIdQueryKey = (
  options: Options<GetApiPatientByIdData>
) => createQueryKey("getApiPatientById", options)

/**
 * Get By Id
 */
export const getApiPatientByIdOptions = (
  options: Options<GetApiPatientByIdData>
) =>
  queryOptions<
    GetApiPatientByIdResponse,
    GetApiPatientByIdError,
    GetApiPatientByIdResponse,
    ReturnType<typeof getApiPatientByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiPatientById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiPatientByIdQueryKey(options),
  })

/**
 * Update
 */
export const putApiPatientByIdMutation = (
  options?: Partial<Options<PutApiPatientByIdData>>
): UseMutationOptions<
  PutApiPatientByIdResponse,
  PutApiPatientByIdError,
  Options<PutApiPatientByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiPatientByIdResponse,
    PutApiPatientByIdError,
    Options<PutApiPatientByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiPatientById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpeciesQueryKey = (options?: Options<GetApiSpeciesData>) =>
  createQueryKey("getApiSpecies", options)

/**
 * Search
 */
export const getApiSpeciesOptions = (options?: Options<GetApiSpeciesData>) =>
  queryOptions<
    GetApiSpeciesResponse,
    GetApiSpeciesError,
    GetApiSpeciesResponse,
    ReturnType<typeof getApiSpeciesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpecies({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpeciesQueryKey(options),
  })

export const getApiSpeciesInfiniteQueryKey = (
  options?: Options<GetApiSpeciesData>
): QueryKey<Options<GetApiSpeciesData>> =>
  createQueryKey("getApiSpecies", options, true)

/**
 * Search
 */
export const getApiSpeciesInfiniteOptions = (
  options?: Options<GetApiSpeciesData>
) => {
  const opts = infiniteQueryOptions<
    GetApiSpeciesResponse,
    GetApiSpeciesError,
    InfiniteData<GetApiSpeciesResponse>,
    QueryKey<Options<GetApiSpeciesData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiSpeciesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiSpeciesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiSpecies({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiSpeciesInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Create
 */
export const postApiSpeciesMutation = (
  options?: Partial<Options<PostApiSpeciesData>>
): UseMutationOptions<
  PostApiSpeciesResponse,
  PostApiSpeciesError,
  Options<PostApiSpeciesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiSpeciesResponse,
    PostApiSpeciesError,
    Options<PostApiSpeciesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiSpecies({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 */
export const deleteApiSpeciesByIdMutation = (
  options?: Partial<Options<DeleteApiSpeciesByIdData>>
): UseMutationOptions<
  DeleteApiSpeciesByIdResponse,
  DeleteApiSpeciesByIdError,
  Options<DeleteApiSpeciesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiSpeciesByIdResponse,
    DeleteApiSpeciesByIdError,
    Options<DeleteApiSpeciesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiSpeciesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiSpeciesByIdQueryKey = (
  options: Options<GetApiSpeciesByIdData>
) => createQueryKey("getApiSpeciesById", options)

/**
 * Get By Id
 */
export const getApiSpeciesByIdOptions = (
  options: Options<GetApiSpeciesByIdData>
) =>
  queryOptions<
    GetApiSpeciesByIdResponse,
    GetApiSpeciesByIdError,
    GetApiSpeciesByIdResponse,
    ReturnType<typeof getApiSpeciesByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiSpeciesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiSpeciesByIdQueryKey(options),
  })

/**
 * Update
 */
export const putApiSpeciesByIdMutation = (
  options?: Partial<Options<PutApiSpeciesByIdData>>
): UseMutationOptions<
  PutApiSpeciesByIdResponse,
  PutApiSpeciesByIdError,
  Options<PutApiSpeciesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiSpeciesByIdResponse,
    PutApiSpeciesByIdError,
    Options<PutApiSpeciesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiSpeciesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentQueryKey = (
  options?: Options<GetApiAppointmentData>
) => createQueryKey("getApiAppointment", options)

/**
 * Find By Date Range
 */
export const getApiAppointmentOptions = (
  options?: Options<GetApiAppointmentData>
) =>
  queryOptions<
    GetApiAppointmentResponse,
    GetApiAppointmentError,
    GetApiAppointmentResponse,
    ReturnType<typeof getApiAppointmentQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointment({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentQueryKey(options),
  })

export const getApiAppointmentInfiniteQueryKey = (
  options?: Options<GetApiAppointmentData>
): QueryKey<Options<GetApiAppointmentData>> =>
  createQueryKey("getApiAppointment", options, true)

/**
 * Find By Date Range
 */
export const getApiAppointmentInfiniteOptions = (
  options?: Options<GetApiAppointmentData>
) => {
  const opts = infiniteQueryOptions<
    GetApiAppointmentResponse,
    GetApiAppointmentError,
    InfiniteData<GetApiAppointmentResponse>,
    QueryKey<Options<GetApiAppointmentData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiAppointmentData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiAppointmentData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getApiAppointment({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getApiAppointmentInfiniteQueryKey(options),
    }
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Create
 */
export const postApiAppointmentMutation = (
  options?: Partial<Options<PostApiAppointmentData>>
): UseMutationOptions<
  PostApiAppointmentResponse,
  PostApiAppointmentError,
  Options<PostApiAppointmentData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiAppointmentResponse,
    PostApiAppointmentError,
    Options<PostApiAppointmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiAppointment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete
 */
export const deleteApiAppointmentByIdMutation = (
  options?: Partial<Options<DeleteApiAppointmentByIdData>>
): UseMutationOptions<
  DeleteApiAppointmentByIdResponse,
  DeleteApiAppointmentByIdError,
  Options<DeleteApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiAppointmentByIdResponse,
    DeleteApiAppointmentByIdError,
    Options<DeleteApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getApiAppointmentByIdQueryKey = (
  options: Options<GetApiAppointmentByIdData>
) => createQueryKey("getApiAppointmentById", options)

/**
 * Get By Id
 */
export const getApiAppointmentByIdOptions = (
  options: Options<GetApiAppointmentByIdData>
) =>
  queryOptions<
    GetApiAppointmentByIdResponse,
    GetApiAppointmentByIdError,
    GetApiAppointmentByIdResponse,
    ReturnType<typeof getApiAppointmentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiAppointmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getApiAppointmentByIdQueryKey(options),
  })

/**
 * Update
 */
export const putApiAppointmentByIdMutation = (
  options?: Partial<Options<PutApiAppointmentByIdData>>
): UseMutationOptions<
  PutApiAppointmentByIdResponse,
  PutApiAppointmentByIdError,
  Options<PutApiAppointmentByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiAppointmentByIdResponse,
    PutApiAppointmentByIdError,
    Options<PutApiAppointmentByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiAppointmentById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
