/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteRouteImport } from "./routes/_public/route"
import { Route as PrivateRouteRouteImport } from "./routes/_private/route"
import { Route as PrivateIndexRouteImport } from "./routes/_private/index"
import { Route as PublicSignInRouteImport } from "./routes/_public/sign-in"
import { Route as PrivateSpeciesRouteImport } from "./routes/_private/species"
import { Route as PrivateProfileRouteImport } from "./routes/_private/profile"
import { Route as PrivatePatientRouteImport } from "./routes/_private/patient"
import { Route as PrivateInventoryRouteImport } from "./routes/_private/inventory"
import { Route as PrivateClientRouteImport } from "./routes/_private/client"
import { Route as PrivateBreedRouteImport } from "./routes/_private/breed"
import { Route as PrivateBillingRouteImport } from "./routes/_private/billing"
import { Route as PrivateAppointmentRouteImport } from "./routes/_private/appointment"
import { Route as PrivatePatientUuidRouteImport } from "./routes/_private/patient.$uuid"
import { Route as PrivateAdminUsersRouteImport } from "./routes/_private/admin.users"

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: "/_private",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateSpeciesRoute = PrivateSpeciesRouteImport.update({
  id: "/species",
  path: "/species",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePatientRoute = PrivatePatientRouteImport.update({
  id: "/patient",
  path: "/patient",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateInventoryRoute = PrivateInventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateClientRoute = PrivateClientRouteImport.update({
  id: "/client",
  path: "/client",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateBreedRoute = PrivateBreedRouteImport.update({
  id: "/breed",
  path: "/breed",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateBillingRoute = PrivateBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAppointmentRoute = PrivateAppointmentRouteImport.update({
  id: "/appointment",
  path: "/appointment",
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePatientUuidRoute = PrivatePatientUuidRouteImport.update({
  id: "/$uuid",
  path: "/$uuid",
  getParentRoute: () => PrivatePatientRoute,
} as any)
const PrivateAdminUsersRoute = PrivateAdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => PrivateRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof PrivateIndexRoute
  "/appointment": typeof PrivateAppointmentRoute
  "/billing": typeof PrivateBillingRoute
  "/breed": typeof PrivateBreedRoute
  "/client": typeof PrivateClientRoute
  "/inventory": typeof PrivateInventoryRoute
  "/patient": typeof PrivatePatientRouteWithChildren
  "/profile": typeof PrivateProfileRoute
  "/species": typeof PrivateSpeciesRoute
  "/sign-in": typeof PublicSignInRoute
  "/admin/users": typeof PrivateAdminUsersRoute
  "/patient/$uuid": typeof PrivatePatientUuidRoute
}
export interface FileRoutesByTo {
  "/": typeof PrivateIndexRoute
  "/appointment": typeof PrivateAppointmentRoute
  "/billing": typeof PrivateBillingRoute
  "/breed": typeof PrivateBreedRoute
  "/client": typeof PrivateClientRoute
  "/inventory": typeof PrivateInventoryRoute
  "/patient": typeof PrivatePatientRouteWithChildren
  "/profile": typeof PrivateProfileRoute
  "/species": typeof PrivateSpeciesRoute
  "/sign-in": typeof PublicSignInRoute
  "/admin/users": typeof PrivateAdminUsersRoute
  "/patient/$uuid": typeof PrivatePatientUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_private": typeof PrivateRouteRouteWithChildren
  "/_public": typeof PublicRouteRouteWithChildren
  "/_private/appointment": typeof PrivateAppointmentRoute
  "/_private/billing": typeof PrivateBillingRoute
  "/_private/breed": typeof PrivateBreedRoute
  "/_private/client": typeof PrivateClientRoute
  "/_private/inventory": typeof PrivateInventoryRoute
  "/_private/patient": typeof PrivatePatientRouteWithChildren
  "/_private/profile": typeof PrivateProfileRoute
  "/_private/species": typeof PrivateSpeciesRoute
  "/_public/sign-in": typeof PublicSignInRoute
  "/_private/": typeof PrivateIndexRoute
  "/_private/admin/users": typeof PrivateAdminUsersRoute
  "/_private/patient/$uuid": typeof PrivatePatientUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/appointment"
    | "/billing"
    | "/breed"
    | "/client"
    | "/inventory"
    | "/patient"
    | "/profile"
    | "/species"
    | "/sign-in"
    | "/admin/users"
    | "/patient/$uuid"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/appointment"
    | "/billing"
    | "/breed"
    | "/client"
    | "/inventory"
    | "/patient"
    | "/profile"
    | "/species"
    | "/sign-in"
    | "/admin/users"
    | "/patient/$uuid"
  id:
    | "__root__"
    | "/_private"
    | "/_public"
    | "/_private/appointment"
    | "/_private/billing"
    | "/_private/breed"
    | "/_private/client"
    | "/_private/inventory"
    | "/_private/patient"
    | "/_private/profile"
    | "/_private/species"
    | "/_public/sign-in"
    | "/_private/"
    | "/_private/admin/users"
    | "/_private/patient/$uuid"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private": {
      id: "/_private"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_private/": {
      id: "/_private/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_public/sign-in": {
      id: "/_public/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    "/_private/species": {
      id: "/_private/species"
      path: "/species"
      fullPath: "/species"
      preLoaderRoute: typeof PrivateSpeciesRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/profile": {
      id: "/_private/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/patient": {
      id: "/_private/patient"
      path: "/patient"
      fullPath: "/patient"
      preLoaderRoute: typeof PrivatePatientRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/inventory": {
      id: "/_private/inventory"
      path: "/inventory"
      fullPath: "/inventory"
      preLoaderRoute: typeof PrivateInventoryRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/client": {
      id: "/_private/client"
      path: "/client"
      fullPath: "/client"
      preLoaderRoute: typeof PrivateClientRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/breed": {
      id: "/_private/breed"
      path: "/breed"
      fullPath: "/breed"
      preLoaderRoute: typeof PrivateBreedRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/billing": {
      id: "/_private/billing"
      path: "/billing"
      fullPath: "/billing"
      preLoaderRoute: typeof PrivateBillingRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/appointment": {
      id: "/_private/appointment"
      path: "/appointment"
      fullPath: "/appointment"
      preLoaderRoute: typeof PrivateAppointmentRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    "/_private/patient/$uuid": {
      id: "/_private/patient/$uuid"
      path: "/$uuid"
      fullPath: "/patient/$uuid"
      preLoaderRoute: typeof PrivatePatientUuidRouteImport
      parentRoute: typeof PrivatePatientRoute
    }
    "/_private/admin/users": {
      id: "/_private/admin/users"
      path: "/admin/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof PrivateAdminUsersRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}

interface PrivatePatientRouteChildren {
  PrivatePatientUuidRoute: typeof PrivatePatientUuidRoute
}

const PrivatePatientRouteChildren: PrivatePatientRouteChildren = {
  PrivatePatientUuidRoute: PrivatePatientUuidRoute,
}

const PrivatePatientRouteWithChildren = PrivatePatientRoute._addFileChildren(
  PrivatePatientRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivateAppointmentRoute: typeof PrivateAppointmentRoute
  PrivateBillingRoute: typeof PrivateBillingRoute
  PrivateBreedRoute: typeof PrivateBreedRoute
  PrivateClientRoute: typeof PrivateClientRoute
  PrivateInventoryRoute: typeof PrivateInventoryRoute
  PrivatePatientRoute: typeof PrivatePatientRouteWithChildren
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateSpeciesRoute: typeof PrivateSpeciesRoute
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateAdminUsersRoute: typeof PrivateAdminUsersRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAppointmentRoute: PrivateAppointmentRoute,
  PrivateBillingRoute: PrivateBillingRoute,
  PrivateBreedRoute: PrivateBreedRoute,
  PrivateClientRoute: PrivateClientRoute,
  PrivateInventoryRoute: PrivateInventoryRoute,
  PrivatePatientRoute: PrivatePatientRouteWithChildren,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateSpeciesRoute: PrivateSpeciesRoute,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAdminUsersRoute: PrivateAdminUsersRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
